# Since the HTML is generated by python scripts, we first need to generate it, then serve it.
# This Dockerfile does both: installs dependencies, generates the map, and serves it.

FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Install system dependencies if any (none obvious from requirements.txt)
# RUN apt-get update && apt-get install -y ...

# Copy requirements and install dependencies
COPY scripts/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project
COPY . .

# Generate the map (assuming this script generates output/geopolitical_map.html)
# We need to make sure the script output directory matches what we serve
RUN python scripts/geopolitical_map.py

# Rename the output file to index.html so it serves by default
RUN mv output/geopolitical_map.html output/index.html

# We'll use python's built-in http server to serve the output directory
# The output directory contains index.html
# We want to serve this on port 8080 (Cloud Run default)
CMD ["python", "-m", "http.server", "8080", "--directory", "output"]
