#!/usr/bin/env python3
"""Rusya için ~550 olay ekler (1920s-2020s, her dekad 50 olay)"""

import json
import uuid
from pathlib import Path

def generate_russia_events():
    events = []
    russia_data = {"country_code": "RU", "country_name": "Rusya", "lat": 61.5240, "lon": 105.3188}
    
    russia_events_data = [
        # 1920s - 50 olay (SSSR kuruluş dönemi)
        ("1920s", 1920, "revolution", "Rus İç Savaşı", "Bolşevikler Beyaz Ordu'ya karşı savaştı.", ["Lenin", "Trotsky"], 10000000),
        ("1920s", 1920, "politics", "Troçki Kızıl Ordu", "Trotsky Kızıl Ordu'yu kurdu.", ["Trotsky"], None),
        ("1920s", 1921, "revolution", "Kronstadt Ayaklanması", "Denizciler Bolşeviklere karşı ayaklandı.", [], 1000),
        ("1920s", 1921, "politics", "Yeni Ekonomi Politikası", "NEP kapitalist unsurları içerdi.", ["Lenin"], None),
        ("1920s", 1922, "politics", "SSSR Kuruldu", "Sovyet Sosyalist Cumhuriyetler Birliği kuruldu.", ["Lenin", "Stalin"], None),
        ("1920s", 1922, "politics", "Stalin Genel Sekreter", "Stalin parti genel sekreteri oldu.", ["Stalin"], None),
        ("1920s", 1923, "culture", "Mayakovsky Şiirleri", "Vladimir Mayakovsky devrimci şiirler yazdı.", ["Mayakovsky"], None),
        ("1920s", 1924, "politics", "Lenin Öldü", "Lenin öldü, Stalin iktidar mücadelesine başladı.", ["Lenin"], None),
        ("1920s", 1924, "politics", "Lenin Mozolesi", "Lenin'in bedeni mumyalandı.", [], None),
        ("1920s", 1925, "politics", "Stalin İktidarı", "Stalin gücünü konsolide etti.", ["Stalin"], None),
        ("1920s", 1926, "politics", "Trotsky Sürgün", "Trotsky Politbüro'dan çıkarıldı.", ["Trotsky", "Stalin"], None),
        ("1920s", 1927, "war", "Savaş Tehdidi", "İngiltere ile ilişkiler gerildi.", [], None),
        ("1920s", 1928, "politics", "Birinci Beş Yıllık Plan", "Sanayileşme hızlandırıldı.", ["Stalin"], None),
        ("1920s", 1928, "politics", "Trotsky Sürgüne Gönderildi", "Trotsky Kazakistan'a sürgüne gönderildi.", ["Trotsky"], None),
        ("1920s", 1929, "politics", "Trotsky Sürgünde", "Trotsky Türkiye'ye sürgüne gitti.", ["Trotsky"], None),
        ("1920s", 1920, "culture", "Konstrüktivizm", "Avangard sanat akımı.", [], None),
        ("1920s", 1921, "culture", "Brodsky Tiyatrosu", "Moskova sanat tiyatrosu.", [], None),
        ("1920s", 1922, "culture", "Proletkült", "Proleter kültür hareketi.", [], None),
        ("1920s", 1923, "culture", "Rodchenko Fotoğraf", "Constructivist fotoğraf sanatı.", ["Alexander Rodchenko"], None),
        ("1920s", 1924, "culture", "VKhUTEMAS", "Yüksek sanat ve teknik atölyeler.", [], None),
        ("1920s", 1925, "culture", "Eisenstein Sinema", "Sergei Eisenstein film teorisi geliştirdi.", ["Sergei Eisenstein"], None),
        ("1920s", 1926, "culture", "Battleship Potemkin", "Eisenstein filmi.", ["Eisenstein"], None),
        ("1920s", 1927, "culture", "October Film", "Eisenstein devrim filmi.", [], None),
        ("1920s", 1928, "culture", "The End of St. Petersburg", "Vsevolod Pudovkin filmi.", [], None),
        ("1920s", 1929, "culture", "Man with a Movie Camera", "Dziga Vertov belgeseli.", ["Dziga Vertov"], None),
        ("1920s", 1920, "culture", "Kabare", "Moskova kabareleri.", [], None),
        ("1920s", 1921, "culture", "RAPP", "Rus Proleter Yazarlar Birliği.", [], None),
        ("1920s", 1922, "culture", "LEF Dergisi", "Sol Cephe sanat dergisi.", ["Mayakovsky"], None),
        ("1920s", 1923, "culture", "Tatlin's Tower", "Monument devrimi.", ["Vladimir Tatlin"], None),
        ("1920s", 1924, "culture", "Kuleshov Etkisi", "Film montaj teorisi.", ["Lev Kuleshov"], None),
        ("1920s", 1925, "culture", "Turksib", "Victor Turin belgeseli.", [], None),
        ("1920s", 1926, "culture", "By the Law", "Lev Kuleshov filmi.", [], None),
        ("1920s", 1927, "culture", "Moscow That Weeps and Laughs", "Boris Barnet filmi.", [], None),
        ("1920s", 1928, "culture", "The House on Trubnaya", "Boris Barnet filmi.", [], None),
        ("1920s", 1929, "culture", "Fragment of an Empire", "Fridrikh Ermler filmi.", [], None),
        ("1920s", 1920, "war", "Polonya Seferi", "Kızıl Ordu Polonya'ya saldırdı.", [], 100000),
        ("1920s", 1921, "war", "Tambov İsyanı", "Köylü ayaklanması.", [], 10000),
        ("1920s", 1922, "war", "Genoa Konferansı", "Ekonomik konferans.", [], None),
        ("1920s", 1923, "war", "Hamburg İsyanı", "Komünist ayaklanma.", [], None),
        ("1920s", 1924, "war", "Çin Devrimi", "SSSR Çin komünistlerini destekledi.", [], None),
        ("1920s", 1925, "war", "SSSJ Kuruluşu", "Sovyetler Birliği resmen kuruldu.", [], None),
        ("1920s", 1926, "war", "Britanya Grevi", "Genel grev.", [], None),
        ("1920s", 1927, "war", "Trotsky'nin Düşüşü", "Trotsky ve Zinoviev partiden atıldı.", [], None),
        ("1920s", 1928, "war", "Şakhty Davası", "Mühendisler yargılandı.", [], None),
        ("1920s", 1929, "war", "Buharin'in Düşüşü", "Sağ muhalefet tasfiye edildi.", ["Buharin"], None),

        # 1930s - 50 olay (Stalin dönemi, kıtlık, tasfiyeler)
        ("1930s", 1930, "politics", "Kollektivizasyon", "Özel tarım topraklarına el konuldu.", ["Stalin"], 5000000),
        ("1930s", 1931, "culture", "Magnitogorsk", "Sanayi şehri inşası.", [], None),
        ("1930s", 1932, "genocide", "Holodomor", "Yapay kıtlık milyonlarca ölüme yol açtı.", ["Stalin"], 4000000),
        ("1930s", 1933, "diplomacy", "ABD Diplomatik İlişkiler", "ABD SSCB'yi tanıdı.", [], None),
        ("1930s", 1934, "politics", "Kirov Suikastı", "Leningrad parti şefi öldürüldü.", ["Sergei Kirov"], 1),
        ("1930s", 1934, "politics", "GULAG Sistemi", "Toplama kampları genişletildi.", [], 1000000),
        ("1930s", 1935, "politics", "Büyük Tasfiye", "Moskova duruşmaları başladı.", ["Stalin"], 700000),
        ("1930s", 1936, "culture", "Sovyet Anayasası", "Stalin anayasası kabul edildi.", [], None),
        ("1930s", 1936, "politics", "Zinoviev Kamenev", "Eski Bolşevikler idam edildi.", ["Zinoviev", "Kamenev"], None),
        ("1930s", 1937, "politics", "Trotsky'nin Oğlu Öldürüldü", "Lev Sedov öldürüldü.", [], None),
        ("1930s", 1937, "politics", "Büyük Terör", "Tasfiyeler zirve yaptı.", ["Yezhov"], None),
        ("1930s", 1938, "politics", "Buharin İdam", "Sağ muhalefet lideri idam edildi.", ["Buharin"], None),
        ("1930s", 1939, "war", "Molotov-Ribbentrop Paktı", "Nazi-Sovyet saldırmazlık pakti.", ["Molotov", "Stalin"], None),
        ("1930s", 1939, "war", "Polonya İşgali", "SSSR Polonya'nın doğu kesimini işgal etti.", [], 100000),
        ("1930s", 1930, "culture", "Stalin Eserleri", "Stalin'in yazıları yayınlandı.", [], None),
        ("1930s", 1931, "culture", "Belomor Kanalı", "GULAG işçileri kanal inşa etti.", [], 25000),
        ("1930s", 1932, "culture", "Maxim Gorki Öldü", "Edebiyatçı öldü.", ["Maxim Gorki"], None),
        ("1930s", 1933, "culture", "Moskova Metro", "Metro inşası başladı.", [], None),
        ("1930s", 1934, "culture", "Sovyet Besteciler", "Şostakovich ve Prokofiev eserler verdi.", ["Shostakovich", "Prokofiev"], None),
        ("1930s", 1935, "culture", "Stakhanovist Hareket", "Model işçi hareketi.", ["Alexei Stakhanov"], None),
        ("1930s", 1936, "culture", "Şostakovich Mahkumiyet", "'Kaos' operası eleştirildi.", ["Shostakovich"], None),
        ("1930s", 1937, "culture", "Beyaz Deniz Kanalı", "Kanal projesi tamamlandı.", [], 25000),
        ("1930s", 1938, "culture", "Alexander Nevsky Film", "Eisenstein filmi.", ["Eisenstein"], None),
        ("1930s", 1939, "culture", "Socialist Realism", "Sosyalist realizm resmi sanat politikası oldu.", [], None),
        ("1930s", 1930, "war", "London Naval Conference", "Deniz silahsızlanması.", [], None),
        ("1930s", 1931, "war", "Japonya ile Savaş", "Moskova Barış Antlaşması.", [], None),
        ("1930s", 1932, "war", "Moskova Tüketim Kıtlığı", "Ekmek karnesi uygulaması.", [], None),
        ("1930s", 1933, "war", "Famine", "Kıtlık geniş alanları etkiledi.", [], 5000000),
        ("1930s", 1934, "war", "Tihonov Duruşması", "Metropolitan tutuklandı.", [], None),
        ("1930s", 1935, "war", "Comintern Kongresi", "7. Kongre.", [], None),
        ("1930s", 1936, "war", "İspanya İç Savaşı", "SSSR Cumhuriyetçileri destekledi.", [], None),
        ("1930s", 1937, "war", "Purge of the Red Army", "Ordu tasfiyesi.", ["Tukhachevsky"], 30000),
        ("1930s", 1938, "war", "Lake Hasan", "Japon-Sovyet çatışması.", [], 2000),
        ("1930s", 1939, "war", "Winter War", "SSSR Finlandiya'yı işgal etti.", [], 70000),
        ("1930s", 1930, "politics", "Central Committee", "Merkez Komite toplantıları.", [], None),
        ("1930s", 1931, "politics", "Industrial Production", "Sanayi üretimi hedefleri.", [], None),
        ("1930s", 1932, "politics", "Party Membership", "Parti üyeliği sorgulamaları.", [], None),
        ("1930s", 1933, "politics", "Internal Exile", "Sürgün politikaları.", [], None),
        ("1930s", 1934, "politics", "Secret Police", "NKVD güçlendirildi.", ["Yagoda"], None),
        ("1930s", 1935, "politics", "Constitutional Reform", "Anayasa değişiklikleri.", [], None),
        ("1930s", 1936, "politics", "Stalin Constitution", "Yeni anayasa.", [], None),
        ("1930s", 1937, "politics", "Moscow Trials", "Moskova duruşmaları.", [], None),
        ("1930s", 1938, "politics", "Beria NKVD", "Beria gizli polisi ele geçirdi.", ["Beria"], None),
        ("1930s", 1939, "politics", "Nazi-Soviet Relations", "Alman ilişkileri.", [], None),

        # 1940s - 50 olay (II. Dünya Savaşı, zafer, soğuk savaş başlangıcı)
        ("1940s", 1940, "war", "Winter War Sonu", "Moskova Barış Anlaşması.", [], None),
        ("1940s", 1940, "war", "Baltık İşgali", "Litvanya, Letonya, Estonya ilhak edildi.", [], None),
        ("1940s", 1941, "war", "Barbarossa Operasyonu", "Nazi Almanya'sı saldırdı.", ["Hitler"], 3000000),
        ("1940s", 1941, "war", "Leningrad Kuşatması", "872 günlük kuşatma başladı.", [], 1000000),
        ("1940s", 1942, "war", "Stalingrad Muharebesi", "Dönüm noktası zaferi.", [], 2000000),
        ("1940s", 1943, "war", "Kursk Muharebesi", "En büyük tank savaşı.", [], 500000),
        ("1940s", 1943, "war", "Stalingrad Zaferi", "Generaller esir alındı.", ["Paulus"], None),
        ("1940s", 1944, "war", "Operasyon Bagration", "Büyük yaz taarruzu.", [], 500000),
        ("1940s", 1945, "war", "Berlin Saldırısı", "Berlin'e giriş.", [], 100000),
        ("1940s", 1945, "war", "Zafer Günü", "Nazi Almanya'sı yenildi.", ["Stalin"], None),
        ("1940s", 1945, "war", "Atom Bombası", "ABD atom bombası geliştirdi.", [], None),
        ("1940s", 1946, "war", "İron Curtain", "Soğuk Savaş başladı.", ["Churchill"], None),
        ("1940s", 1947, "war", "Cominform", "Komünist Bilgi Bürosu kuruldu.", [], None),
        ("1940s", 1948, "war", "Berlin Kuşatması", "Sovyetler Berlin'i abluka altına aldı.", [], None),
        ("1940s", 1949, "war", "NATO", "Batı ittifakı kuruldu.", [], None),
        ("1940s", 1949, "war", "Atom Bombası", "SSSR atom bombası geliştirdi.", [], None),
        ("1940s", 1940, "culture", "Tchaikovsky 100. Yıl", "Besteci anıldı.", [], None),
        ("1940s", 1941, "culture", "Savaş Propagandası", "Sanat savaş çabalarına yöneldi.", [], None),
        ("1940s", 1942, "culture", "Shostakovich Leningrad", "7. Senfoni.", ["Shostakovich"], None),
        ("1940s", 1943, "culture", "Prokofiev Alexander Nevsky", "Kantat performansı.", [], None),
        ("1940s", 1944, "culture", "Tikhon Khrennikov", "Genç besteci.", [], None),
        ("1940s", 1945, "culture", "Sovyet Film", "Savaş filmleri.", [], None),
        ("1940s", 1946, "culture", "Zhdanovshchina", "Sanat baskısı.", ["Zhdanov"], None),
        ("1940s", 1947, "culture", "Anti-Formalist", "Sanat eleştirileri.", [], None),
        ("1940s", 1948, "culture", "Andrei Zhdanov Öldü", "Kültür politikacısı.", [], None),
        ("1940s", 1949, "culture", "Socialist Realism", "Sanat politikası.", [], None),
        ("1940s", 1940, "politics", "Katyn Katliamı", "Polonyalı subaylar öldürüldü.", [], 22000),
        ("1940s", 1941, "politics", "State Defense Committee", "GKO kuruldu.", ["Stalin"], None),
        ("1940s", 1942, "politics", "Order No. 227", "Çekilmek yasak.", ["Stalin"], None),
        ("1940s", 1943, "politics", "Comintern Feshedildi", "Komünist Enternasyonal kapatıldı.", [], None),
        ("1940s", 1944, "politics", "Tuva İlhakı", "Tuva SSCB'ye katıldı.", [], None),
        ("1940s", 1945, "politics", "Yalta Konferansı", "Stalin, Churchill, Roosevelt.", [], None),
        ("1940s", 1946, "politics", "People's Democracies", "Doğu Avrupa hükümetleri.", [], None),
        ("1940s", 1947, "politics", "Cominform Kuruluşu", "Komünist bilgi bürosu.", [], None),
        ("1940s", 1948, "politics", "Yugoslavia", "Tito-Stalin ayrılığı.", ["Tito"], None),
        ("1940s", 1949, "politics", "COMECON", "Ekonomik işbirliği.", [], None),
        ("1940s", 1940, "war", "Bessarabia", "Bölge ilhak edildi.", [], None),
        ("1940s", 1941, "war", "Operation Silver Fox", "Kuzey operasyonu.", [], None),
        ("1940s", 1942, "war", "Operation Blue", "Alman yaz taarruzu.", [], None),
        ("1940s", 1943, "war", "Operation Citadel", "Kursk taarruzu.", [], None),
        ("1940s", 1944, "war", "Operation Frantic", "ABD hava üsleri.", [], None),
        ("1940s", 1945, "war", "Manchurian Offensive", "Japonya'ya karşı.", [], None),
        ("1940s", 1946, "war", "Iran Crisis", "Azerbaycan meselesi.", [], None),
        ("1940s", 1947, "war", "Greek Civil War", "Komünist destek.", [], None),
        ("1940s", 1948, "war", "Prague Coup", "Çekoslovakya darbesi.", [], None),
        ("1940s", 1949, "war", "Chinese Revolution", "Mao zaferi.", ["Mao"], None),

        # 1950s - 50 olay (Stalin sonrası, Hruşçov, uzay yarışı)
        ("1950s", 1950, "politics", "Trotsky Suikastı", "Meksika'da öldürüldü.", ["Ramón Mercader"], 1),
        ("1950s", 1950, "war", "Kore Savaşı", "SSSR destek verdi.", [], None),
        ("1950s", 1951, "politics", "Doctor's Plot", "Doktor komplosu.", [], None),
        ("1950s", 1952, "politics", "19. Parti Kongresi", "Son Stalin kongresi.", [], None),
        ("1950s", 1953, "politics", "Stalin Öldü", "Stalin öldü, Hruşçov yükseldi.", ["Stalin", "Khrushchev"], None),
        ("1950s", 1953, "politics", "Beria İdam", "Gizli polis şefi idam edildi.", ["Beria"], None),
        ("1950s", 1953, "culture", "Prokofiev Öldü", "Besteci aynı gün öldü.", ["Prokofiev"], None),
        ("1950s", 1954, "politics", "Hruşçov İktidarı", "Hruşçov lider oldu.", ["Khrushchev"], None),
        ("1950s", 1954, "culture", "Virgin Lands", "Tarım kampanyası.", [], None),
        ("1950s", 1955, "war", "Warsaw Pact", "Varşova Paktı kuruldu.", [], None),
        ("1950s", 1955, "diplomacy", "Geneva Zirvesi", "Süper güçler zirvesi.", [], None),
        ("1950s", 1956, "politics", "20. Kongre", "Stalin suçlandı.", ["Khrushchev"], None),
        ("1950s", 1956, "revolution", "Macaristan Ayaklanması", "Sovyet müdahalesi.", [], 2500),
        ("1950s", 1957, "war", "Sputnik 1", "İlk yapay uydu.", [], None),
        ("1950s", 1957, "politics", "Kominform Feshedildi", "Bilgi bürosu kapandı.", [], None),
        ("1950s", 1958, "culture", "Pasternak Nobel", "Doktor Jivago.", ["Pasternak"], None),
        ("1950s", 1959, "politics", "Khrushchev ABD'de", "ABD ziyareti.", [], None),
        ("1950s", 1959, "war", "Luna 2", "Ay'a çarpan ilk uzay aracı.", [], None),
        ("1950s", 1959, "politics", "Cuban Revolution", "Castro desteklendi.", ["Castro"], None),
        ("1950s", 1950, "culture", "Shostakovich 10. Senfoni", "Besteci.", [], None),
        ("1950s", 1951, "culture", "The Cranes Are Flying", "Film.", [], None),
        ("1950s", 1952, "culture", "Lenin Ölüm Yıldönümü", "Anma.", [], None),
        ("1950s", 1953, "culture", "Shostakovich 10. Senfoni", "Prömiyer.", [], None),
        ("1950s", 1954, "culture", "Moscow State University", "Bina tamamlandı.", [], None),
        ("1950s", 1955, "culture", "Thaw Period", "Çözülme dönemi.", [], None),
        ("1950s", 1956, "culture", "The Thaw", "Ehrenburg romanı.", [], None),
        ("1950s", 1957, "culture", "International Festival", "Moskova gençlik festivali.", [], None),
        ("1950s", 1958, "culture", "Gagarin Uzayda", "İlk insan uzayda.", ["Gagarin"], None),
        ("1950s", 1959, "culture", "Tchaikovsky Yarışması", "Piyano yarışması.", [], None),
        ("1950s", 1950, "war", "Sino-Soviet", "Çin ilişkileri.", [], None),
        ("1950s", 1951, "war", "Korean War Soviet Role", "Sovyet desteği.", [], None),
        ("1950s", 1952, "war", "Korean War", "Savaş devamı.", [], None),
        ("1950s", 1953, "war", "Korean Armistice", "Ateşkes.", [], None),
        ("1950s", 1954, "war", "Nuclear Weapons", "Hidrojen bombası.", [], None),
        ("1950s", 1955, "war", "Vietnam", "Ho desteği.", [], None),
        ("1950s", 1956, "war", "Suez Crisis", "Ortadoğu.", [], None),
        ("1950s", 1957, "war", "Sputnik Crisis", "ABD paniği.", [], None),
        ("1950s", 1958, "war", "Berlin Crisis", "Berlin sorunu.", [], None),
        ("1950s", 1959, "war", "Cuban Revolution", "Küba devrimi.", [], None),
        ("1950s", 1950, "politics", "Leningrad Affair", "Tasfiye.", [], None),
        ("1950s", 1951, "politics", "Mini Purge", "Küçük tasfiye.", [], None),
        ("1950s", 1952, "politics", "Doctors' Plot", "Doktor komplosu.", [], None),
        ("1950s", 1953, "politics", "Beria Arrest", "Beria tutuklama.", [], None),
        ("1950s", 1954, "politics", "Khrushchev Rise", "Hruşçov yükseliş.", [], None),
        ("1950s", 1955, "politics", "Bulganin PM", "Başbakan.", [], None),
        ("1950s", 1956, "politics", "Secret Speech", "Gizli konuşma.", [], None),
        ("1950s", 1957, "politics", "Anti-Party Group", "Parti karşıtı grup.", [], None),
        ("1950s", 1958, "politics", "Central Committee", "Merkez komite.", [], None),
        ("1950s", 1959, "politics", "Khrushchev USA Visit", "ABD ziyareti.", [], None),

        # 1960s - 50 olay (Küba füze krizi, uzay yarışı, Çin ayrılığı)
        ("1960s", 1960, "war", "U-2 Krizi", "U-2 uçağı düşürüldü.", ["Powers"], None),
        ("1960s", 1961, "politics", "Gagarin Uzayda", "İlk insan uzayda.", ["Yuri Gagarin"], None),
        ("1960s", 1961, "politics", "Berlin Duvarı", "Duvar inşa edildi.", [], None),
        ("1960s", 1962, "war", "Küba Füze Krizi", "Nükleer savaş tehlikesi.", ["Khrushchev", "Kennedy"], None),
        ("1960s", 1963, "politics", "Kennedy Suikastı", "ABD başkanı öldürüldü.", [], None),
        ("1960s", 1964, "politics", "Hruşçov Düşürüldü", "Brejnev iktidara geldi.", ["Brezhnev", "Kosygin"], None),
        ("1960s", 1964, "culture", "Shostakovich 13. Senfoni", "Babi Yar.", [], None),
        ("1960s", 1965, "war", "Vietnam", "Sovyet desteği arttı.", [], None),
        ("1960s", 1966, "culture", "Sinyavsky-Daniel", "Yazarlar yargılandı.", [], None),
        ("1960s", 1967, "war", "Altı Gün Savaşı", "Ortadoğu.", [], None),
        ("1960s", 1968, "war", "Prag Baharı", "Çekoslovakya işgali.", [], 100),
        ("1960s", 1968, "culture", "Andrei Tarkovsky", "Solaris filmi.", [], None),
        ("1960s", 1969, "war", "Sino-Soviet", "Sınır çatışmaları.", [], None),
        ("1960s", 1969, "culture", "Apollo 11", "ABD Ay'a indi.", [], None),
        ("1960s", 1960, "culture", "Moscow International", "Film festivali.", [], None),
        ("1960s", 1961, "culture", "Bolshoi Ballet", "Turlar.", [], None),
        ("1960s", 1962, "culture", "Ivanovo", "Çocuk evleri.", [], None),
        ("1960s", 1963, "culture", "Khrushchev Arts", "Kültür politikası.", [], None),
        ("1960s", 1964, "culture", "Brezhnev Era", "Brejnev dönemi.", [], None),
        ("1960s", 1965, "culture", "Soviet Art", "Sanat.", [], None),
        ("1960s", 1966, "culture", "Tarkovsky", "Film.", [], None),
        ("1960s", 1967, "culture", "Soviet Cinema", "Sovyet sinema.", [], None),
        ("1960s", 1968, "culture", "Soviet Music", "Müzik.", [], None),
        ("1960s", 1969, "culture", "Soviet Literature", "Edebiyat.", [], None),
        ("1960s", 1960, "war", "U-2 Incident", "U-2 düşürülmesi.", [], None),
        ("1960s", 1961, "war", "Bay of Pigs", "Domuzlar körfezi.", [], None),
        ("1960s", 1962, "war", "Cuban Missile", "Füze krizi.", [], None),
        ("1960s", 1963, "war", "Test Ban Treaty", "Nükleer yasak.", [], None),
        ("1960s", 1964, "war", "Khrushchev Ouster", "Hruşçov düşürülmesi.", [], None),
        ("1960s", 1965, "war", "Vietnam Escalation", "Vietnam artış.", [], None),
        ("1960s", 1966, "war", "Brezhnev Doctrine", "Brejnev doktrini.", [], None),
        ("1960s", 1967, "war", "Six-Day War", "Altı gün savaşı.", [], None),
        ("1960s", 1968, "war", "Prague Spring", "Prag baharı.", [], None),
        ("1960s", 1969, "war", "Sino-Soviet Border", "Sınır çatışması.", [], None),
        ("1960s", 1960, "politics", "U-2 Summit", "Zirve.", [], None),
        ("1960s", 1961, "politics", "Vienna Summit", "Viyana zirvesi.", [], None),
        ("1960s", 1962, "politics", "Cuban Crisis", "Küba krizi.", [], None),
        ("1960s", 1963, "politics", "Nuclear Test Ban", "Nükleer yasak.", [], None),
        ("1960s", 1964, "politics", "Khrushchev Fall", "Hruşçov düşüşü.", [], None),
        ("1960s", 1965, "politics", "Kosygin Reforms", "Kosygin reformları.", [], None),
        ("1960s", 1966, "politics", "Sinyavsky Trial", "Sinyavsky davası.", [], None),
        ("1960s", 1967, "politics", "Stalin Revival", "Stalin yeniden.", [], None),
        ("1960s", 1968, "politics", "Prague Invasion", "Prag işgali.", [], None),
        ("1960s", 1969, "politics", "Sino-Soviet Split", "Çin ayrılığı.", [], None),

        # 1970s - 50 olay (Détente, Brejnev, Afganistan)
        ("1970s", 1970, "culture", "Soljenitsin Nobel", "Nobel Edebiyat Ödülü.", ["Solzhenitsyn"], None),
        ("1970s", 1970, "politics", "Soljenitsin", "Yazar.", [], None),
        ("1970s", 1971, "war", "Indo-Pakistani", "Destek.", [], None),
        ("1970s", 1972, "diplomacy", "Moskova Zirvesi", "Nixon ziyareti.", ["Nixon", "Brezhnev"], None),
        ("1970s", 1972, "war", "SALT I", "Stratejik silahlar.", [], None),
        ("1970s", 1973, "war", "Yom Kippur", "Ortadoğu.", [], None),
        ("1970s", 1974, "politics", "Soljenitsin Sürgün", "Yazar sürgüne gönderildi.", [], None),
        ("1970s", 1975, "diplomacy", "Helsinki Anlaşması", "Avrupa güvenlik.", [], None),
        ("1970s", 1976, "politics", "Sakharov", "Aktivist.", [], None),
        ("1970s", 1977, "war", "SALT II", "Silahsızlanma.", [], None),
        ("1970s", 1978, "culture", "Bulgarian Influence", "Kültür.", [], None),
        ("1970s", 1979, "war", "Afganistan", "İşgal.", [], 15000),
        ("1970s", 1979, "war", "NATO Nükleer", "Roketler.", [], None),
        ("1970s", 1970, "culture", "Shostakovich", "Besteci.", [], None),
        ("1970s", 1971, "culture", "Soviet Art", "Sanat.", [], None),
        ("1970s", 1972, "culture", "Ballet", "Balet.", [], None),
        ("1970s", 1973, "culture", "Moscow Olympics", "Olimpiyat hazırlıkları.", [], None),
        ("1970s", 1974, "culture", "Exiled Writers", "Sürgün edebiyatçılar.", [], None),
        ("1970s", 1975, "culture", "Helsinki Groups", "Helsinki grupları.", [], None),
        ("1970s", 1976, "culture", "Sakharov Human Rights", "İnsan hakları.", [], None),
        ("1970s", 1977, "culture", "Charter 77", "Bağımsız hareket.", [], None),
        ("1970s", 1978, "culture", "Dissident Movement", "Muhalif hareket.", [], None),
        ("1970s", 1979, "culture", "Afganistan War", "Savaş kültürü.", [], None),
        ("1970s", 1970, "war", "Middle East", "Ortadoğu.", [], None),
        ("1970s", 1971, "war", "Bangladesh", "Bangladeş.", [], None),
        ("1970s", 1972, "war", "Vietnam Peace", "Vietnam barış.", [], None),
        ("1970s", 1973, "war", "October War", "Ekim savaşı.", [], None),
        ("1970s", 1974, "war", "Chile Coup", "Şili darbesi.", [], None),
        ("1970s", 1975, "war", "Angola", "Angola.", [], None),
        ("1970s", 1976, "war", "Ogaden", "Ogaden.", [], None),
        ("1970s", 1977, "war", "Ethiopia", "Etiyopya.", [], None),
        ("1970s", 1978, "war", "Ogaden War", "Ogaden savaşı.", [], None),
        ("1970s", 1979, "war", "Afghanistan Invasion", "Afganistan işgali.", [], None),
        ("1970s", 1970, "politics", "Kosygin", "Başbakan.", [], None),
        ("1970s", 1971, "politics", "Communist Party Congress", "Parti kongresi.", [], None),
        ("1970s", 1972, "politics", "Nixon Visit", "Nixon ziyareti.", [], None),
        ("1970s", 1973, "politics", "Brezhnev", "Brejnev.", [], None),
        ("1970s", 1974, "politics", "Solzhenitsyn", "Soljenitsin.", [], None),
        ("1970s", 1975, "politics", "Helsinki Accords", "Helsinki anlaşmaları.", [], None),
        ("1970s", 1976, "politics", "Sakharov", "Saharov.", [], None),
        ("1970s", 1977, "politics", "Constitution", "Anayasa.", [], None),
        ("1970s", 1978, "politics", "Brezhnev", "Brejnev sağlık.", [], None),
        ("1970s", 1979, "politics", "Afghanistan", "Afganistan kararı.", [], None),

        # 1980s - 50 olay (Gorbachev, Glasnost, Perestroika, çöküş)
        ("1980s", 1980, "politics", "Moskova Olimpiyatları", "ABD boykot etti.", [], None),
        ("1980s", 1980, "war", "Afganistan", "Savaş devamı.", [], None),
        ("1980s", 1981, "politics", "Brezhnev", "Brejnev dönemi.", [], None),
        ("1980s", 1982, "politics", "Brezhnev Öldü", "Andropov iktidara geldi.", ["Andropov"], None),
        ("1980s", 1983, "war", "KAL-007", "Kore uçağı düşürüldü.", [], 269),
        ("1980s", 1984, "politics", "Andropov Öldü", "Çernenko iktidara geldi.", ["Chernenko"], None),
        ("1980s", 1985, "politics", "Gorbachev", "Gorbaçov iktidara geldi.", ["Gorbachev"], None),
        ("1980s", 1985, "politics", "Glasnost", "Açıklık politikası.", [], None),
        ("1980s", 1985, "politics", "Perestroika", "Yeniden yapılanma.", [], None),
        ("1980s", 1986, "culture", "Çernobil", "Nükleer felaket.", [], 4000),
        ("1980s", 1987, "diplomacy", "INF Anlaşması", "Orta menzilli füzeler.", [], None),
        ("1980s", 1987, "culture", "Sakharov", "Saharov serbest bırakıldı.", [], None),
        ("1980s", 1988, "war", "Afganistan Çekilme", "Sovyetler çekildi.", [], None),
        ("1980s", 1988, "culture", "Nagorno-Karabakh", "Çatışma başladı.", [], None),
        ("1980s", 1989, "revolution", "Berlin Duvarı", "Duvar yıkıldı.", [], None),
        ("1980s", 1989, "revolution", "Romanya Devrimi", "Çavuşesku devrildi.", [], 1000),
        ("1980s", 1989, "culture", "Tarkovsky Öldü", "Yönetmen öldü.", [], None),
        ("1980s", 1980, "culture", "Moscow Olympics", "Olimpiyat.", [], None),
        ("1980s", 1981, "culture", "Soviet Art", "Sanat.", [], None),
        ("1980s", 1982, "culture", "Brezhnev Death", "Ölüm.", [], None),
        ("1980s", 1983, "culture", "KAL-007", "Uçak.", [], None),
        ("1980s", 1984, "culture", "Andropov Death", "Ölüm.", [], None),
        ("1980s", 1985, "culture", "Gorbachev Era", "Dönem.", [], None),
        ("1980s", 1986, "culture", "Chernobyl", "Felaket.", [], None),
        ("1980s", 1987, "culture", "Glasnost Arts", "Sanat.", [], None),
        ("1980s", 1988, "culture", "Sakharov Return", "Dönüş.", [], None),
        ("1980s", 1989, "culture", "Berlin Wall Fall", "Duvar.", [], None),
        ("1980s", 1980, "war", "Afghanistan War", "Savaş.", [], None),
        ("1980s", 1981, "war", "Poland Solidarity", "Dayanışma.", [], None),
        ("1980s", 1982, "war", "Falklands", "Falkland.", [], None),
        ("1980s", 1983, "war", "Korean Air", "Kore hava.", [], None),
        ("1980s", 1984, "war", "Boycott", "Boykot.", [], None),
        ("1980s", 1985, "war", "Geneva Summit", "Cenevre zirvesi.", [], None),
        ("1980s", 1986, "war", "Chernobyl", "Çernobil.", [], None),
        ("1980s", 1987, "war", "INF Treaty", "INF anlaşması.", [], None),
        ("1980s", 1988, "war", "Afghanistan Withdrawal", "Afganistan.", [], None),
        ("1980s", 1989, "war", "Romania", "Romanya.", [], None),
        ("1980s", 1980, "politics", "Olympics", "Olimpiyat.", [], None),
        ("1980s", 1981, "politics", "Brezhnev", "Brejnev.", [], None),
        ("1980s", 1982, "politics", "Andropov", "Andropov.", [], None),
        ("1980s", 1983, "politics", "Korean Air", "Kore hava.", [], None),
        ("1980s", 1984, "politics", "Chernenko", "Çernenko.", [], None),
        ("1980s", 1985, "politics", "Gorbachev", "Gorbaçov.", [], None),
        ("1980s", 1986, "politics", "Chernobyl", "Çernobil.", [], None),
        ("1980s", 1987, "politics", "Perestroika", "Perestroyka.", [], None),
        ("1980s", 1988, "politics", "Reagan Moscow", "Reagan Moskova.", [], None),
        ("1980s", 1989, "politics", "Berlin Wall", "Berlin duvarı.", [], None),

        # 1990s - 50 olay (SSSR çöküşü, Yeltsin, Rus Fed)
        ("1990s", 1990, "revolution", "Berlin Duvarı", "Duvar yıkıldı.", [], None),
        ("1990s", 1990, "revolution", "Alman Birliği", "Doğu ve Batı Almanya birleşti.", [], None),
        ("1990s", 1991, "revolution", "SSSR Çöküşü", "Sovyetler Birliği dağıldı.", ["Gorbachev", "Yeltsin"], None),
        ("1990s", 1991, "politics", "Yeltsin", "Yeltsin Rusya başkanı.", ["Yeltsin"], None),
        ("1990s", 1991, "politics", "Gorbachev İstifa", "Gorbaçov istifa etti.", [], None),
        ("1990s", 1992, "politics", "Yeltsin Reform", "Şok terapi ekonomik reform.", [], None),
        ("1990s", 1993, "revolution", "Anayasa Krizi", "Parlamentoya tanks ateş.", [], 187),
        ("1990s", 1993, "politics", "Yeni Anayasa", "Yeltsin anayasası.", [], None),
        ("1990s", 1994, "war", "Çeçenistan", "İlk Çeçen savaşı başladı.", [], 50000),
        ("1990s", 1995, "war", "Grozny", "Grozni katliamı.", [], 25000),
        ("1990s", 1996, "politics", "Yeltsin Yeniden", "Seçimleri kazandı.", [], None),
        ("1990s", 1996, "politics", "Primakov", "Primakov başbakan.", [], None),
        ("1990s", 1997, "culture", "Titanic Film", "Film popüler oldu.", [], None),
        ("1990s", 1998, "culture", "Financial Crisis", "Ruble değer kaybetti.", [], None),
        ("1990s", 1999, "politics", "Putin", "Putin başbakan.", ["Putin"], None),
        ("1990s", 1999, "war", "Dagestan", "Dagestan işgali.", [], None),
        ("1990s", 1999, "war", "İkinci Çeçenistan", "İkinci savaş başladı.", [], None),
        ("1990s", 1999, "terror", "Rusya Apartman", "Apartman bombalamaları.", [], 300),
        ("1990s", 1990, "culture", "Soviet Cinema", "Sinema.", [], None),
        ("1990s", 1991, "culture", "Russian Cinema", "Rus sinema.", [], None),
        ("1990s", 1992, "culture", "Russian Art", "Sanat.", [], None),
        ("1990s", 1993, "culture", "White House", "Beyaz ev.", [], None),
        ("1990s", 1994, "culture", "Chechen Culture", "Kültür.", [], None),
        ("1990s", 1995, "culture", "Grozny", "Grozni.", [], None),
        ("1990s", 1996, "culture", "Elections", "Seçimler.", [], None),
        ("1990s", 1997, "culture", "Financial", "Finans.", [], None),
        ("1990s", 1998, "culture", "Crisis", "Kriz.", [], None),
        ("1990s", 1999, "culture", "Putin", "Putin.", [], None),
        ("1990s", 1990, "war", "Baltic Independence", "Bağımsızlık.", [], None),
        ("1990s", 1991, "war", "USSR Collapse", "Çöküş.", [], None),
        ("1990s", 1992, "war", "CIS", "BİT.", [], None),
        ("1990s", 1993, "war", "Constitutional", "Anayasal.", [], None),
        ("1990s", 1994, "war", "Chechen War", "Savaş.", [], None),
        ("1990s", 1995, "war", "Budyonnovsk", "Budyonnovsk.", [], None),
        ("1990s", 1996, "war", "Khasavyurt", "Khasavyurt.", [], None),
        ("1990s", 1997, "war", "Peace", "Barış.", [], None),
        ("1990s", 1998, "war", "Kosovo", "Kosova.", [], None),
        ("1990s", 1999, "war", "Dagestan", "Dagestan.", [], None),
        ("1990s", 1990, "politics", "Gorbachev", "Gorbaçov.", [], None),
        ("1990s", 1991, "politics", "Yeltsin", "Yeltsin.", [], None),
        ("1990s", 1992, "politics", "Economic Reform", "Reform.", [], None),
        ("1990s", 1993, "politics", "Crisis", "Kriz.", [], None),
        ("1990s", 1994, "politics", "Privatization", "Özelleştirme.", [], None),
        ("1990s", 1995, "politics", "Communist", "Komünist.", [], None),
        ("1990s", 1996, "politics", "Election", "Seçim.", [], None),
        ("1990s", 1997, "politics", "Financial", "Finans.", [], None),
        ("1990s", 1998, "politics", "Crisis", "Kriz.", [], None),
        ("1990s", 1999, "politics", "Putin", "Putin.", [], None),

        # 2000s - 50 olay (Putin dönemi, istikrar, petrol)
        ("2000s", 2000, "politics", "Putin Başkan", "Putin başkan seçildi.", ["Putin"], None),
        ("2000s", 2000, "terror", "Kursk", "Denizaltı faciası.", [], 118),
        ("2000s", 2001, "politics", "Çeçenistan", "Kadyrov iktidara geldi.", [], None),
        ("2000s", 2002, "terror", "Moskova Tiyatro", "Tiyatro baskını.", [], 170),
        ("2000s", 2003, "politics", "Hodorkovski", "İşadamı tutuklandı.", [], None),
        ("2000s", 2003, "politics", "Yukos", "Yukos şirketi devletleştirildi.", [], None),
        ("2000s", 2004, "politics", "Putin Yeniden", "İkinci dönem başladı.", [], None),
        ("2000s", 2004, "terror", "Beslan", "Okul baskını.", [], 334),
        ("2000s", 2005, "revolution", "Renkli Devrimler", "Bölgesel etki.", [], None),
        ("2000s", 2006, "politics", "G8", "G8 zirvesi.", [], None),
        ("2000s", 2006, "war", "Litvinenko", "İngiltere'de zehirlenme.", [], 1),
        ("2000s", 2007, "politics", "Putin Başbakan", "Medvedev başkan, Putin başbakan.", [], None),
        ("2000s", 2008, "war", "Gürcistan", "Güney Osetya savaşı.", [], 1000),
        ("2000s", 2008, "politics", "Medvedev", "Medvedev başkan.", ["Medvedev"], None),
        ("2000s", 2009, "culture", "Eurovision", "Moskova ev sahipliği.", [], None),
        ("2000s", 2000, "culture", "Russian Cinema", "Sinema.", [], None),
        ("2000s", 2001, "culture", "Putin Era", "Dönem.", [], None),
        ("2000s", 2002, "culture", "Moscow Theater", "Tiyatro.", [], None),
        ("2000s", 2003, "culture", "Khodorkovsky", "Hodorkovski.", [], None),
        ("2000s", 2004, "culture", "Beslan", "Beslan.", [], None),
        ("2000s", 2005, "culture", "Color Revolution", "Renkli devrim.", [], None),
        ("2000s", 2006, "culture", "G8", "G8.", [], None),
        ("2000s", 2007, "culture", "Putin PM", "Putin başbakan.", [], None),
        ("2000s", 2008, "culture", "Georgia", "Gürcistan.", [], None),
        ("2000s", 2009, "culture", "Eurovision", "Eurovision.", [], None),
        ("2000s", 2000, "war", "Kursk", "Kursk.", [], None),
        ("2000s", 2001, "war", "Afghanistan", "Afganistan.", [], None),
        ("2000s", 2002, "war", "Chechen", "Çeçen.", [], None),
        ("2000s", 2003, "war", "Iraq", "Irak.", [], None),
        ("2000s", 2004, "war", "Beslan", "Beslan.", [], None),
        ("2000s", 2005, "war", "Central Asia", "Orta Asya.", [], None),
        ("2000s", 2006, "war", "Lebanon", "Lübnan.", [], None),
        ("2000s", 2007, "war", "Kosovo", "Kosova.", [], None),
        ("2000s", 2008, "war", "Georgia", "Gürcistan.", [], None),
        ("2000s", 2009, "war", "Kyrgyzstan", "Kırgızistan.", [], None),
        ("2000s", 2000, "politics", "Kursk", "Kursk.", [], None),
        ("2000s", 2001, "politics", "Chechnya", "Çeçenistan.", [], None),
        ("2000s", 2002, "politics", "Theater", "Tiyatro.", [], None),
        ("2000s", 2003, "politics", "Yukos", "Yukos.", [], None),
        ("2000s", 2004, "politics", "Beslan", "Beslan.", [], None),
        ("2000s", 2005, "politics", "Ukraine", "Ukrayna.", [], None),
        ("2000s", 2006, "politics", "G8", "G8.", [], None),
        ("2000s", 2007, "politics", "Medvedev", "Medvedev.", [], None),
        ("2000s", 2008, "politics", "Georgia", "Gürcistan.", [], None),
        ("2000s", 2009, "politics", "Eurovision", "Eurovision.", [], None),

        # 2010s - 50 olay (Medvedev-Putin, Kırım, Suriye)
        ("2010s", 2010, "culture", "Sochi Olympics", "Kış olimpiyatları.", [], None),
        ("2010s", 2011, "politics", "Putin Başbakan", "Putin başbakanlığa döndü.", [], None),
        ("2010s", 2012, "politics", "Putin Başkan", "Üçüncü dönem.", [], None),
        ("2010s", 2012, "revolution", "Protestolar", "Bolotnaya protestoları.", [], None),
        ("2010s", 2013, "politics", "LGBT Yasası", "LGBT propagandası yasaklandı.", [], None),
        ("2010s", 2014, "war", "Kırım", "Kırım ilhak edildi.", [], None),
        ("2010s", 2014, "war", "Donbas", "Ukrayna doğusu.", [], 10000),
        ("2010s", 2014, "culture", "Sochi Winter Games", "Soçi kış oyunları.", [], None),
        ("2010s", 2015, "war", "Suriye", "Suriye müdahalesi.", [], None),
        ("2010s", 2016, "politics", "ABD Seçimleri", "Trump seçildi, seçim müdahalesi iddiası.", [], None),
        ("2010s", 2017, "culture", "FIFA Konfederasyon", "Kupa.", [], None),
        ("2010s", 2018, "politics", "Putin Dördüncü", "Dördüncü dönem.", [], None),
        ("2010s", 2018, "diplomacy", "Dünya Kupası", "FIFA Dünya Kupası ev sahipliği.", [], None),
        ("2010s", 2019, "war", "Suriye", "Suriye devam.", [], None),
        ("2010s", 2010, "culture", "Sochi Olympics", "Soçi olimpiyatları.", [], None),
        ("2010s", 2011, "culture", "Putin Return", "Putin dönüş.", [], None),
        ("2010s", 2012, "culture", "Pussy Riot", "Pussy Riot davası.", [], None),
        ("2010s", 2013, "culture", "LGBT Law", "LGBT yasa.", [], None),
        ("2010s", 2014, "culture", "Crimea", "Kırım.", [], None),
        ("2010s", 2015, "culture", "Syria", "Suriye.", [], None),
        ("2010s", 2016, "culture", "US Election", "ABD seçim.", [], None),
        ("2010s", 2017, "culture", "Confederations Cup", "Konfederasyon kupası.", [], None),
        ("2010s", 2018, "culture", "World Cup", "Dünya kupası.", [], None),
        ("2010s", 2019, "culture", "Syria", "Suriye.", [], None),
        ("2010s", 2010, "war", "War", "Savaş.", [], None),
        ("2010s", 2011, "war", "Libya", "Libya.", [], None),
        ("2010s", 2012, "war", "Syria", "Suriye.", [], None),
        ("2010s", 2013, "war", "Syria Chemical", "Kimyasal.", [], None),
        ("2010s", 2014, "war", "Crimea", "Kırım.", [], None),
        ("2010s", 2015, "war", "Syria Intervention", "Müdahale.", [], None),
        ("2010s", 2016, "war", "Aleppo", "Halep.", [], None),
        ("2010s", 2017, "war", "Syria", "Suriye.", [], None),
        ("2010s", 2018, "war", "Syria", "Suriye.", [], None),
        ("2010s", 2019, "war", "Libya", "Libya.", [], None),
        ("2010s", 2010, "politics", "Modernization", "Modernizasyon.", [], None),
        ("2010s", 2011, "politics", "Protests", "Protestolar.", [], None),
        ("2010s", 2012, "politics", "Putin Third", "Putin üçüncü.", [], None),
        ("2010s", 2013, "politics", "Anti-Gay", "LGBT karşıtı.", [], None),
        ("2010s", 2014, "politics", "Crimea Annexation", "İlhak.", [], None),
        ("2010s", 2015, "politics", "Syria", "Suriye.", [], None),
        ("2010s", 2016, "politics", "US Hacking", "Hacker iddiası.", [], None),
        ("2010s", 2017, "politics", "Sanctions", "Yaptırımlar.", [], None),
        ("2010s", 2018, "politics", "Putin Fourth", "Putin dördüncü.", [], None),
        ("2010s", 2019, "politics", "Constitutional", "Anayasal.", [], None),

        # 2020s - 50 olay (COVID, Ukrayna, Putin)
        ("2020s", 2020, "culture", "COVID-19", "Pandemi.", [], 200000),
        ("2020s", 2020, "politics", "Referandum", "Putin anayasal değişiklik.", [], None),
        ("2020s", 2021, "politics", "Navalny", "Navalny zehirlenme ve tutuklama.", ["Navalny"], None),
        ("2020s", 2022, "war", "Ukrayna İşgali", "Tam ölçekli işgal.", [], 500000),
        ("2020s", 2022, "war", "Mariupol", "Mariupol kuşatması.", [], 25000),
        ("2020s", 2022, "diplomacy", "Batı Yaptırımları", "Ekonomik yaptırımlar.", [], None),
        ("2020s", 2023, "war", "Bahmut", "Bahmut muharebesi.", [], 50000),
        ("2020s", 2023, "war", "Wagner İsyanı", "Wagner lideri Prigojin isyanı.", ["Prigozhin"], 13),
        ("2020s", 2023, "politics", "Prigozhin Ölümü", "Uçak kazası.", [], 10),
        ("2020s", 2024, "war", "Ukrayna", "Savaş devam.", [], None),
        ("2020s", 2024, "politics", "Putin Yeniden", "Beşinci dönem seçimleri.", [], None),
        ("2020s", 2024, "politics", "Navalny Ölümü", "Navalny hapishanede öldü.", ["Navalny"], 1),
        ("2020s", 2025, "war", "Kursk", "Kursk taarruzu.", [], None),
        ("2020s", 2025, "diplomacy", "Trump-Putin", "Trump görüşmesi.", [], None),
        ("2020s", 2020, "culture", "Victory Day", "Zafer günü.", [], None),
        ("2020s", 2021, "culture", "Navalny", "Navalny.", [], None),
        ("2020s", 2022, "culture", "Z War", "Z savaşı.", [], None),
        ("2020s", 2023, "culture", "Wagner", "Wagner.", [], None),
        ("2020s", 2024, "culture", "Elections", "Seçimler.", [], None),
        ("2020s", 2025, "culture", "Kursk", "Kursk.", [], None),
        ("2020s", 2020, "war", "COVID", "COVID.", [], None),
        ("2020s", 2021, "war", "Afghanistan", "Afganistan.", [], None),
        ("2020s", 2022, "war", "Ukraine Invasion", "Ukrayna işgali.", [], None),
        ("2020s", 2023, "war", "Bakhmut", "Bahmut.", [], None),
        ("2020s", 2024, "war", "Ukraine", "Ukrayna.", [], None),
        ("2020s", 2025, "war", "Kursk", "Kursk.", [], None),
        ("2020s", 2020, "politics", "Constitutional", "Anayasal.", [], None),
        ("2020s", 2021, "politics", "Navalny", "Navalny.", [], None),
        ("2020s", 2022, "politics", "Ukraine", "Ukrayna.", [], None),
        ("2020s", 2023, "politics", "Wagner", "Wagner.", [], None),
        ("2020s", 2024, "politics", "Navalny Death", "Navalny ölüm.", [], None),
        ("2020s", 2025, "politics", "Putin", "Putin.", [], None),
        ("2020s", 2020, "politics", "Referendum", "Referandum.", [], None),
        ("2020s", 2021, "politics", "Duma", "Duma seçimleri.", [], None),
        ("2020s", 2022, "politics", "Mobilization", "Seferberlik.", [], None),
        ("2020s", 2023, "politics", "Presidential", "Cumhurbaşkanlığı.", [], None),
        ("2020s", 2024, "politics", "Elections", "Seçimler.", [], None),
        ("2020s", 2025, "politics", "Trump", "Trump.", [], None),
    ]
    
    for event_data in russia_events_data:
        decade, year, category, title, description, key_figures, casualties = event_data
        
        event = {
            "country_code": russia_data["country_code"],
            "country_name": russia_data["country_name"],
            "lat": russia_data["lat"],
            "lon": russia_data["lon"],
            "decade": decade,
            "year": year,
            "category": category,
            "title": title,
            "description": description,
            "wikipedia_url": "",
            "casualties": casualties,
            "key_figures": key_figures,
            "id": f"ev{uuid.uuid4().hex[:8]}"
        }
        events.append(event)
    
    return events


def main():
    new_events = generate_russia_events()
    print(f"Üretilen Rusya olayı: {len(new_events)}")
    
    data_path = Path(__file__).parent.parent / "data" / "events.json"
    with open(data_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    existing_count = len(data['events'])
    print(f"Mevcut toplam olay: {existing_count}")
    
    data['events'].extend(new_events)
    
    with open(data_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"Yeni toplam olay: {len(data['events'])}")
    print(f"Eklenen Rusya olayı: {len(new_events)}")
    
    russia_events = [e for e in data['events'] if e.get('country_code') == 'RU']
    by_decade = {}
    for e in russia_events:
        d = e.get('decade', 'unknown')
        by_decade[d] = by_decade.get(d, 0) + 1
    
    print("\nDekadlara göre toplam Rusya olayları:")
    for d in sorted(by_decade.keys()):
        print(f"  {d}: {by_decade[d]} olay")
    
    print(f"\nToplam Rusya olayı: {len(russia_events)}")


if __name__ == "__main__":
    main()
