#!/usr/bin/env python3
"""ABD için ~550 olay ekler (1920s-2020s, her dekad 50 olay)"""

import json
import uuid
from pathlib import Path

def generate_usa_events():
    events = []
    usa_data = {"country_code": "US", "country_name": "Amerika Birleşik Devletleri", "lat": 37.0902, "lon": -95.7129}
    
    usa_events_data = [
        # 1920s - 50 olay
        ("1920s", 1920, "culture", "Prohibition Başladı", "18. Değişiklik ile alkol yasağı yürürlüğe girdi.", [], None),
        ("1920s", 1920, "politics", "Kadınların Seçme Hakkı", "19. Değişiklik kadınlara oy hakkı verdi.", ["Susan B. Anthony"], None),
        ("1920s", 1920, "culture", "Jazz Age Başladı", "Caz müziği ve Charleston dansı popüler oldu.", ["Louis Armstrong"], None),
        ("1920s", 1921, "politics", "Warren G. Harding Başkan", "Warren G. Harding başkanlığa seçildi.", ["Warren G. Harding"], None),
        ("1920s", 1921, "culture", "The Sheik Film", "Rudolph Valentino'nun filmi büyük hit oldu.", ["Rudolph Valentino"], None),
        ("1920s", 1922, "culture", "Radio Broadcasts", "İlk ticari radyo istasyonları yayına başladı.", [], None),
        ("1920s", 1922, "politics", "Lincoln Memorial Açıldı", "Washington'da Lincoln Anıtı açıldı.", [], None),
        ("1920s", 1923, "politics", "Teapot Dome Skandalı", "Büyük petrol rüşvet skandalı patlak verdi.", [], None),
        ("1920s", 1923, "politics", "Calvin Coolidge Başkan", "Coolidge, Harding'in ölümüyle başkan oldu.", ["Calvin Coolidge"], None),
        ("1920s", 1924, "culture", "George Gershwin Rhapsody in Blue", "Gershwin'in bestesi prömiyer yaptı.", ["George Gershwin"], None),
        ("1920s", 1924, "politics", "Coolidge Yeniden Seçildi", "Coolidge seçimleri kazandı.", ["Calvin Coolidge"], None),
        ("1920s", 1925, "culture", "The Great Gatsby", "F. Scott Fitzgerald'ın romanı yayınlandı.", ["F. Scott Fitzgerald"], None),
        ("1920s", 1925, "culture", "Scopes Monkey Trial", "Evrim dersi veren öğretmenin davası.", ["Clarence Darrow"], None),
        ("1920s", 1926, "culture", "Route 66", "Ünlü anayol Route 66 açıldı.", [], None),
        ("1920s", 1926, "culture", "Don Juan Film", "John Barrymore sessiz filmde oynadı.", ["John Barrymore"], None),
        ("1920s", 1927, "culture", "The Jazz Singer", "İlk sesli film vizyona girdi.", ["Al Jolson"], None),
        ("1920s", 1927, "culture", "Lindbergh Transatlantic Uçuş", "Charles Lindbergh tek başına Atlas Okyanusu'nu geçti.", ["Charles Lindbergh"], None),
        ("1920s", 1927, "culture", "Babe Ruth 60 Home Run", "Babe Ruth rekor kırdı.", ["Babe Ruth"], None),
        ("1920s", 1927, "politics", "Sacco and Vanzetti", "İtalyan anarşistler idam edildi.", [], None),
        ("1920s", 1928, "politics", "Herbert Hoover Başkan", "Hoover seçimleri kazandı.", ["Herbert Hoover"], None),
        ("1920s", 1928, "culture", "Walt Disney Mickey Mouse", "Mickey Mouse karakteri yaratıldı.", ["Walt Disney"], None),
        ("1920s", 1929, "culture", "St. Valentine's Day Massacre", "Al Capone'nin düzenlediği katliam.", ["Al Capone"], 7),
        ("1920s", 1929, "culture", "Black Tuesday", "Borsa çöktü, Büyük Buhran başladı.", [], None),
        ("1920s", 1920, "culture", "Babe Ruth Yankees'e", "Babe Ruth New York Yankees'e transfer oldu.", ["Babe Ruth"], None),
        ("1920s", 1921, "culture", "The Kid Film", "Charlie Chaplin filmi vizyona girdi.", ["Charlie Chaplin"], None),
        ("1920s", 1922, "culture", "MGM Logo", "Metro-Goldwyn-Mayer logosu kullanılmaya başlandı.", [], None),
        ("1920s", 1923, "culture", "Hollywoodland Tabelası", "Hollywood tabelası dikildi.", [], None),
        ("1920s", 1924, "culture", "NHL Kuruldu", "National Hockey League kuruldu.", [], None),
        ("1920s", 1925, "culture", "Al Capone Chicago", "Al Capone Chicago'da organize suçu ele geçirdi.", ["Al Capone"], None),
        ("1920s", 1926, "culture", "Winnie-the-Pooh", "A.A. Milne'in kitabı yayınlandı.", ["A.A. Milne"], None),
        ("1920s", 1927, "culture", "Mount Rushmore Başladı", "Heykel projesi başladı.", ["Gutzon Borglum"], None),
        ("1920s", 1928, "culture", " sliced bread", "İlk dilimlenmiş ekmek satıldı.", [], None),
        ("1920s", 1929, "culture", "Academy Awards", "İlk Oscar töreni düzenlendi.", [], None),
        ("1920s", 1920, "culture", "KDKA Radio", "İlk ticari radyo lisansı verildi.", [], None),
        ("1920s", 1921, "culture", "Bessie Coleman Pilot", "İlk siyahi kadın pilot lisans aldı.", ["Bessie Coleman"], None),
        ("1920s", 1922, "culture", "Reader's Digest", "Dergi ilk kez yayınlandı.", ["DeWitt Wallace"], None),
        ("1920s", 1923, "culture", "Time Magazine", "Time dergisi ilk kez yayınlandı.", [], None),
        ("1920s", 1924, "culture", "NFL Kuruldu", "National Football League kurumsal yapıya kavuştu.", [], None),
        ("1920s", 1925, "culture", "Tennessee vs. John Scopes", "Evrim davası.", [], None),
        ("1920s", 1926, "culture", "Carter Family", "İlk country müzik kaydı yapıldı.", ["The Carter Family"], None),
        ("1920s", 1927, "culture", "The Harlem Renaissance", "Harlem Rönesansı zirve yaptı.", ["Langston Hughes", "Zora Neale Hurston"], None),
        ("1920s", 1928, "culture", "Amos 'n' Andy", "Radyo dizisi popüler oldu.", [], None),
        ("1920s", 1929, "culture", "Museum of Modern Art", "MoMA New York'ta açıldı.", [], None),
        ("1920s", 1921, "culture", "Polo Grounds", "New York Giants baseball stadyumu.", [], None),
        ("1920s", 1923, "culture", "Yankee Stadium Açıldı", "The House That Ruth Built.", [], None),
        ("1920s", 1924, "culture", "Ellis Island", "Göçmen işlemleri zirve yaptı.", [], None),
        ("1920s", 1926, "culture", "Houdini Öldü", "Sihirbaz Harry Houdini öldü.", ["Harry Houdini"], None),
        ("1920s", 1927, "culture", "The Cotton Club", "Harlem'de ünlü gece kulübü açıldı.", [], None),
        ("1920s", 1928, "culture", "Steamboat Willie", "Walt Disney'in ilk Mickey Mouse animasyonu.", ["Walt Disney"], None),

        # 1930s - 50 olay
        ("1930s", 1930, "politics", "Smoot-Hawley Tariff Act", "Koruyucu gümrük vergileri yürürlüğe girdi.", [], None),
        ("1930s", 1930, "culture", "Pluto Keşfedildi", "Clyde Tombaugh Plüton'u keşfetti.", ["Clyde Tombaugh"], None),
        ("1930s", 1931, "culture", "Empire State Building", "Empire State Binası açıldı.", [], None),
        ("1930s", 1931, "culture", "The Star-Spangled Banner", "Ulusal marş resmi olarak kabul edildi.", [], None),
        ("1930s", 1932, "politics", "Franklin D. Roosevelt Başkan", "FDR seçildi.", ["Franklin D. Roosevelt"], None),
        ("1930s", 1932, "politics", "Reconstruction Finance Corporation", "RFC ekonomik yardım kurumu kuruldu.", [], None),
        ("1930s", 1933, "politics", "New Deal Başladı", "FDR ekonomik programını başlattı.", ["Franklin D. Roosevelt"], None),
        ("1930s", 1933, "culture", "Prohibition Bitti", "21. Değişiklik alkol yasağını kaldırdı.", [], None),
        ("1930s", 1933, "culture", "King Kong Film", "King Kong filmi vizyona girdi.", [], None),
        ("1930s", 1934, "politics", "Securities and Exchange Commission", "SEC kuruldu.", [], None),
        ("1930s", 1934, "culture", "Dust Bowl", "Toz fırtınaları Ortabatı'yı vurdu.", [], None),
        ("1930s", 1935, "politics", "Social Security Act", "Sosyal güvenlik sistemi kuruldu.", ["Frances Perkins"], None),
        ("1930s", 1935, "culture", "Monopoly Oyunu", "Monopoly oyunu satışa çıktı.", [], None),
        ("1930s", 1936, "culture", "Gone with the Wind", "Rüzgar Gibi Geçti filmi vizyona girdi.", ["Vivien Leigh", "Clark Gable"], None),
        ("1930s", 1936, "politics", "Hoover Dam Tamamlandı", "Baraj projesi bitti.", [], None),
        ("1930s", 1937, "politics", "FDR İkinci Dönem", "FDR ikinci kez seçildi.", ["Franklin D. Roosevelt"], None),
        ("1930s", 1937, "culture", "Disney's Snow White", "Pamuk Prenses ilk uzun animasyon film oldu.", ["Walt Disney"], None),
        ("1930s", 1937, "war", "Panay Olayı", "Japon uçakları USS Panay'ı batırdı.", [], 3),
        ("1930s", 1938, "culture", "Superman Çizgi Roman", "Superman ilk kez yayınlandı.", ["Jerry Siegel", "Joe Shuster"], None),
        ("1930s", 1938, "culture", "The War of the Worlds Radyo", "Orson Welles radyo yayını panik yarattı.", ["Orson Welles"], None),
        ("1930s", 1939, "culture", "The Wizard of Oz", "Oz Büyücüsü filmi vizyona girdi.", ["Judy Garland"], None),
        ("1930s", 1939, "war", "Manhattan Project Başladı", "Atom bombası projesi başladı.", [], None),
        ("1930s", 1930, "culture", "The Shadow", "Radyo dizisi başladı.", [], None),
        ("1930s", 1931, "culture", "Dracula Film", "Bela Lugosi filmi.", ["Bela Lugosi"], None),
        ("1930s", 1932, "culture", "Amelia Earhart", "Amelia Earhart Atlas Okyanusu'nu geçti.", ["Amelia Earhart"], None),
        ("1930s", 1933, "culture", "Golden Gate Bridge", "Köprü inşaatına başlandı.", [], None),
        ("1930s", 1934, "culture", "Bonnie and Clyde", "Çete üyeleri öldürüldü.", ["Bonnie Parker", "Clyde Barrow"], None),
        ("1930s", 1935, "culture", "Parker Brothers", "Monopoly oyunu popüler oldu.", [], None),
        ("1930s", 1936, "culture", "Life Magazine", "Life dergisi ilk kez yayınlandı.", ["Henry Luce"], None),
        ("1930s", 1937, "culture", "Hindenburg Felaketi", "Zeplin patladı.", [], 36),
        ("1930s", 1938, "culture", "Action Comics #1", "İlk Superman çizgi romanı.", [], None),
        ("1930s", 1939, "culture", "Gone with the Wind Prömiyer", "Film Atlanta'da gösterildi.", [], None),
        ("1930s", 1930, "culture", "Betty Boop", "Çizgi film karakteri yaratıldı.", [], None),
        ("1930s", 1931, "culture", "Frankenstein Film", "Boris Karloff filmi.", ["Boris Karloff"], None),
        ("1930s", 1932, "culture", "Shirley Temple", "Shirley Temple çocuk yıldız oldu.", ["Shirley Temple"], None),
        ("1930s", 1933, "culture", "The Lone Ranger", "Radyo dizisi başladı.", [], None),
        ("1930s", 1934, "culture", "It Happened One Night", "Frank Capra filmi Oscar kazandı.", ["Frank Capra", "Clark Gable"], None),
        ("1930s", 1935, "culture", "Mutiny on the Bounty", "Film vizyona girdi.", ["Clark Gable"], None),
        ("1930s", 1936, "culture", "Jesse Owens Berlin", "Jesse Owens 4 altın madalya kazandı.", ["Jesse Owens"], None),
        ("1930s", 1937, "culture", "Spam", "Hormel Spam satışa çıktı.", [], None),
        ("1930s", 1938, "culture", "Looney Tunes", "Bugs Bunny karakteri yaratıldı.", [], None),
        ("1930s", 1939, "culture", "Mr. Smith Goes to Washington", "Frank Capra filmi vizyona girdi.", ["James Stewart"], None),
        ("1930s", 1930, "culture", "The Mickey Mouse Club", "Kulüp kuruldu.", [], None),
        ("1930s", 1932, "culture", "Radio City Music Hall", "New York'ta açıldı.", [], None),
        ("1930s", 1934, "culture", "Will Rogers", "Will Rogers popüler komedyen.", ["Will Rogers"], None),
        ("1930s", 1935, "culture", "Penguin Books", "Penguin kitap yayınevi kuruldu.", [], None),
        ("1930s", 1936, "culture", "Bing Crosby", "Bing Crosby zirve yaptı.", ["Bing Crosby"], None),
        ("1930s", 1937, "culture", "Disney's Snow White Prömiyer", "Animasyon film prömiyeri.", [], None),
        ("1930s", 1939, "culture", "Nylon", "DuPont nylon'u piyasaya sürdü.", [], None),

        # 1940s - 50 olay
        ("1940s", 1940, "war", "Selective Training and Service Act", "Askerlik sistemi kuruldu.", [], None),
        ("1940s", 1940, "culture", "Tom and Jerry", "Çizgi film serisi başladı.", [], None),
        ("1940s", 1941, "war", "Pearl Harbor Saldırısı", "Japonya Pearl Harbor'a saldırdı, ABD II. Dünya Savaşı'na girdi.", [], 2403),
        ("1940s", 1941, "politics", "FDR Dördüncü Dönem", "FDR dördüncü kez seçildi.", ["Franklin D. Roosevelt"], None),
        ("1940s", 1942, "war", "Manhattan Project", "Atom bombası geliştirme projesi başladı.", ["J. Robert Oppenheimer"], None),
        ("1940s", 1942, "war", "Battle of Midway", "Pasifik'te dönüm noktası zaferi.", [], None),
        ("1940s", 1942, "culture", "Casablanca Film", "Casablanca filmi vizyona girdi.", ["Humphrey Bogart", "Ingrid Bergman"], None),
        ("1940s", 1943, "war", "Tehran Konferansı", "FDR, Churchill ve Stalin bir araya geldi.", ["FDR", "Churchill", "Stalin"], None),
        ("1940s", 1943, "culture", "The Pentagon", "Pentagon binası tamamlandı.", [], None),
        ("1940s", 1944, "war", "D-Day Normandy", "Normandiya Çıkarması.", ["Dwight D. Eisenhower"], None),
        ("1940s", 1944, "war", "Battle of the Bulge", "Ardenler Taarruzu.", [], None),
        ("1940s", 1944, "politics", "GI Bill", "Veteranlara yardım yasası.", [], None),
        ("1940s", 1945, "war", "Yalta Konferansı", "FDR, Churchill, Stalin Yalta'da.", ["FDR", "Churchill", "Stalin"], None),
        ("1940s", 1945, "war", "Hiroshima ve Nagasaki", "Atom bombaları atıldı.", [], 200000),
        ("1940s", 1945, "politics", "FDR Öldü", "Roosevelt öldü, Truman başkan oldu.", ["Harry S. Truman"], None),
        ("1940s", 1945, "war", "United Nations", "Birleşmiş Milletler kuruldu.", [], None),
        ("1940s", 1946, "war", "Nürnberg Mahkemeleri", "Nazi savaş suçluları yargılandı.", [], None),
        ("1940s", 1946, "culture", "ENIAC", "İlk elektronik bilgisayar.", [], None),
        ("1940s", 1947, "war", "Truman Doctrine", "Sovyet yayılmasına karşı politika.", ["Harry S. Truman"], None),
        ("1940s", 1947, "war", "Marshall Planı", "Avrupa'nın yeniden yapılandırılması yardımı.", ["George Marshall"], None),
        ("1940s", 1947, "politics", "Hollywood Kara Listesi", "Komünist avı Hollywood'u vurdu.", [], None),
        ("1940s", 1947, "politics", "Jackie Robinson", "Jackie Robinson beyaz liginde oynayan ilk siyahi beyzbolcu.", ["Jackie Robinson"], None),
        ("1940s", 1948, "war", "Berlin Kuşatması", "Sovyetler Berlin'i kuşattı.", [], None),
        ("1940s", 1948, "politics", "Truman Yeniden", "Truman seçimleri sürpriz şekilde kazandı.", ["Harry S. Truman"], None),
        ("1940s", 1949, "war", "NATO Kuruldu", "Kuzey Atlantik Paktı.", [], None),
        ("1940s", 1949, "war", "Soviet Atom Bombası", "Sovyetler atom bombası geliştirdi.", [], None),
        ("1940s", 1940, "culture", "Fantasia", "Disney filmi vizyona girdi.", ["Walt Disney"], None),
        ("1940s", 1941, "culture", "Citizen Kane", "Orson Welles şaheseri.", ["Orson Welles"], None),
        ("1940s", 1942, "culture", "Yankee Doodle Dandy", "James Cagney filmi.", ["James Cagney"], None),
        ("1940s", 1943, "culture", "The Song of Bernadette", "Jennifer Jones filmi.", [], None),
        ("1940s", 1944, "culture", "Going My Way", "Bing Crosby filmi.", ["Bing Crosby"], None),
        ("1940s", 1945, "culture", "The Lost Weekend", "Alkol bağımlılığı filmi.", ["Ray Milland"], None),
        ("1940s", 1946, "culture", "The Best Years of Our Lives", "Savaş sonrası filmi.", [], None),
        ("1940s", 1947, "culture", "Gentleman's Agreement", "Anti-semitizm filmi.", ["Gregory Peck"], None),
        ("1940s", 1948, "culture", "Laurence Olivier Hamlet", "Shakespeare uyarlaması.", ["Laurence Olivier"], None),
        ("1940s", 1949, "culture", "All the King's Men", "Siyasi drama.", ["Broderick Crawford"], None),
        ("1940s", 1940, "culture", "The Great Dictator", "Charlie Chaplin filmi.", ["Charlie Chaplin"], None),
        ("1940s", 1941, "culture", "How Green Was My Valley", "John Ford filmi.", ["John Ford"], None),
        ("1940s", 1942, "culture", "Mrs. Miniver", "Savaş filmi.", ["Greer Garson"], None),
        ("1940s", 1943, "culture", "Double Indemnity", "Film noir.", ["Billy Wilder"], None),
        ("1940s", 1944, "culture", "Gaslight", "Ingrid Bergman filmi.", ["Ingrid Bergman"], None),
        ("1940s", 1945, "culture", "Mildred Pierce", "Joan Crawford filmi.", ["Joan Crawford"], None),
        ("1940s", 1946, "culture", "It's a Wonderful Life", "Frank Capra filmi.", ["James Stewart"], None),
        ("1940s", 1947, "culture", "Miracle on 34th Street", "Noel filmi.", ["Maureen O'Hara"], None),
        ("1940s", 1948, "culture", "The Treasure of the Sierra Madre", "John Huston filmi.", ["Humphrey Bogart"], None),
        ("1940s", 1949, "culture", "A Streetcar Named Desire", "Tennessee Williams uyarlaması.", ["Marlon Brando"], None),

        # 1950s - 50 olay
        ("1950s", 1950, "war", "Kore Savaşı", "Kore Savaşı başladı.", [], 36000),
        ("1950s", 1950, "politics", "McCarthyism", "Komünist avı zirve yaptı.", ["Joseph McCarthy"], None),
        ("1950s", 1951, "war", "Truman Kore'yi Fethetti", "Truman savaşı yönetti.", [], None),
        ("1950s", 1951, "culture", "The Day the Earth Stood Still", "Bilim kurgu filmi.", [], None),
        ("1950s", 1952, "politics", "Dwight D. Eisenhower Başkan", "Eisenhower seçildi.", ["Dwight D. Eisenhower"], None),
        ("1950s", 1952, "culture", "American Bandstand", "Müzik programı başladı.", ["Dick Clark"], None),
        ("1950s", 1953, "politics", "Korean Armistice", "Kore Ateşkes Anlaşması.", [], None),
        ("1950s", 1953, "culture", "DNA Keşfi", "Watson ve Crick DNA yapısını açıkladı.", ["James Watson", "Francis Crick"], None),
        ("1950s", 1954, "politics", "Brown v. Board of Education", "Tahsilde ayrım yasağı kaldırıldı.", [], None),
        ("1950s", 1954, "war", "McCarthy Hearings", "McCarthy duruşmaları.", [], None),
        ("1950s", 1954, "culture", "Elvis Presley", "Elvis ilk single'ını çıkardı.", ["Elvis Presley"], None),
        ("1950s", 1955, "culture", "Disneyland Açıldı", "Disneyland Kaliforniya'da açıldı.", ["Walt Disney"], None),
        ("1950s", 1955, "culture", "Rebel Without a Cause", "James Dean filmi.", ["James Dean"], None),
        ("1950s", 1955, "culture", "Montgomery Bus Boykotu", "Rosa Parks olayı.", ["Rosa Parks", "Martin Luther King Jr."], None),
        ("1950s", 1956, "politics", "Interstate Highway System", "Otoyol sistemi başladı.", ["Dwight D. Eisenhower"], None),
        ("1950s", 1956, "culture", "Elvis Johnny Carson Show", "Elvis TV'de.", ["Elvis Presley"], None),
        ("1950s", 1957, "war", "Sputnik", "Sovyet uydusu fırlatıldı.", [], None),
        ("1950s", 1957, "politics", "Little Rock Nine", "Okul bütünleşme krizi.", [], None),
        ("1950s", 1957, "culture", "West Side Story", "Broadway müzikali prömiyer yaptı.", [], None),
        ("1950s", 1958, "culture", "NASA Kuruldu", "Uzay ajansı kuruldu.", [], None),
        ("1950s", 1958, "culture", "Hula Hoop", "Hula hoop çılgınlığı.", [], None),
        ("1950s", 1959, "culture", "Alaska ve Hawaii Eyalet", "49. ve 50. eyaletler.", [], None),
        ("1950s", 1959, "culture", "The Twilight Zone", "TV dizisi başladı.", ["Rod Serling"], None),
        ("1950s", 1950, "culture", "Peanuts Çizgi Roman", "Charles Schulz çizgi romanı.", ["Charles Schulz"], None),
        ("1950s", 1951, "culture", "The Catcher in the Rye", "J.D. Salinger romanı.", ["J.D. Salinger"], None),
        ("1950s", 1952, "culture", "The Today Show", "NBC sabah programı.", [], None),
        ("1950s", 1953, "culture", "Playboy Dergisi", "Hugh Hefner dergiyi kurdu.", ["Hugh Hefner"], None),
        ("1950s", 1954, "culture", "Godzilla", "Japon canavarı filmi ABD'de gösterildi.", [], None),
        ("1950s", 1955, "culture", "Gunsmoke", "TV dizisi başladı.", [], None),
        ("1950s", 1956, "culture", "In God We Trust", "Dolar üzerine yazıldı.", [], None),
        ("1950s", 1957, "culture", "On the Road", "Jack Kerouac romanı.", ["Jack Kerouac"], None),
        ("1950s", 1958, "culture", "The Hula Hoop", "Oyuncak çılgınlığı.", [], None),
        ("1950s", 1959, "culture", "Barbie Bebek", "Barbie bebek satışa çıktı.", [], None),
        ("1950s", 1950, "culture", "Rin Tin Tin", "TV dizisi.", [], None),
        ("1950s", 1951, "culture", "Color Television", "Renkli TV yayınları başladı.", [], None),
        ("1950s", 1952, "culture", "The Greatest Show on Earth", "Cecil B. DeMille filmi.", ["Cecil B. DeMille"], None),
        ("1950s", 1953, "culture", "Roman Holiday", "Audrey Hepburn filmi.", ["Audrey Hepburn"], None),
        ("1950s", 1954, "culture", "The Wild One", "Marlon Brando filmi.", ["Marlon Brando"], None),
        ("1950s", 1955, "culture", "The $64,000 Question", "TV yarışması.", [], None),
        ("1950s", 1956, "culture", "The Ten Commandments", "Cecil B. DeMille filmi.", ["Charlton Heston"], None),
        ("1950s", 1957, "culture", "The Bridge on the River Kwai", "David Lean filmi.", ["Alec Guinness"], None),
        ("1950s", 1958, "culture", "The Defiant Ones", "Tony Curtis ve Sidney Poitier filmi.", [], None),
        ("1950s", 1959, "culture", "Some Like It Hot", "Billy Wilder filmi.", ["Marilyn Monroe", "Tony Curtis"], None),
        ("1950s", 1950, "culture", "Your Show of Shows", "Sid Caesar TV programı.", ["Sid Caesar"], None),
        ("1950s", 1951, "culture", "I Love Lucy", "TV sitcomu başladı.", ["Lucille Ball", "Desi Arnaz"], None),
        ("1950s", 1952, "culture", "Singin' in the Rain", "Gene Kelly filmi.", ["Gene Kelly"], None),
        ("1950s", 1953, "culture", "From Here to Eternity", "Burt Lancaster filmi.", [], None),
        ("1950s", 1954, "culture", "On the Waterfront", "Marlon Brando filmi.", [], None),

        # 1960s - 50 olay
        ("1960s", 1960, "politics", "JFK Başkan", "John F. Kennedy seçildi.", ["John F. Kennedy"], None),
        ("1960s", 1960, "culture", "To Kill a Mockingbird", "Harper Lee romanı yayınlandı.", ["Harper Lee"], None),
        ("1960s", 1961, "politics", "Bay of Pigs", "Küba çıkarması başarısız oldu.", [], None),
        ("1960s", 1961, "culture", "West Side Story Filmi", "Film müzikal Oscar kazandı.", [], None),
        ("1960s", 1962, "war", "Küba Füze Krizi", "Sovyet füzeleri Küba'da, nükleer kriz.", ["JFK", "Khrushchev"], None),
        ("1960s", 1962, "culture", "The Beatles", "Beatles ABD'de ilk kez çaldı.", ["The Beatles"], None),
        ("1960s", 1963, "politics", "JFK Suikastı", "Kennedy öldürüldü.", ["Lee Harvey Oswald"], 1),
        ("1960s", 1963, "politics", "Martin Luther King Jr. Washington", "I Have a Dream konuşması.", ["Martin Luther King Jr."], None),
        ("1960s", 1964, "politics", "Civil Rights Act", "Medeni haklar yasası kabul edildi.", ["Lyndon B. Johnson"], None),
        ("1960s", 1964, "culture", "The Beatles Ed Sullivan", "Beatles TV'de.", ["The Beatles"], None),
        ("1960s", 1965, "politics", "Voting Rights Act", "Oy hakkı yasası.", ["Martin Luther King Jr."], None),
        ("1960s", 1965, "war", "Vietnam Savaşı", "ABD askerleri Vietnam'a girdi.", [], 58000),
        ("1960s", 1965, "culture", "The Sound of Music", "Julie Andrews filmi.", ["Julie Andrews"], None),
        ("1960s", 1966, "culture", "Star Trek", "TV dizisi başladı.", ["Gene Roddenberry"], None),
        ("1960s", 1966, "culture", "The Beach Boys", "Pet Sounds albümü.", ["Brian Wilson"], None),
        ("1960s", 1967, "culture", "Summer of Love", "Hippilerin San Francisco'daki yazı.", [], None),
        ("1960s", 1967, "culture", "The Graduate", "Dustin Hoffman filmi.", ["Dustin Hoffman", "Anne Bancroft"], None),
        ("1960s", 1968, "politics", "MLK Suikastı", "Martin Luther King Jr. öldürüldü.", ["James Earl Ray"], 1),
        ("1960s", 1968, "politics", "RFK Suikastı", "Robert F. Kennedy öldürüldü.", ["Sirhan Sirhan"], 1),
        ("1960s", 1968, "culture", "Apollo 8", "Ay'a ilk insanlı yolculuk.", [], None),
        ("1960s", 1969, "culture", "Apollo 11", "Neil Armstrong Ay'a ilk adımı attı.", ["Neil Armstrong", "Buzz Aldrin"], None),
        ("1960s", 1969, "culture", "Woodstock", "3 günlük müzik festivali.", [], None),
        ("1960s", 1960, "culture", "Psycho Film", "Alfred Hitchcock filmi.", ["Alfred Hitchcock"], None),
        ("1960s", 1961, "culture", "Breakfast at Tiffany's", "Audrey Hepburn filmi.", ["Audrey Hepburn"], None),
        ("1960s", 1962, "culture", "Lawrence of Arabia", "Peter O'Toole filmi.", ["Peter O'Toole"], None),
        ("1960s", 1963, "culture", "The Birds", "Alfred Hitchcock filmi.", [], None),
        ("1960s", 1964, "culture", "Mary Poppins", "Julie Andrews filmi.", ["Julie Andrews"], None),
        ("1960s", 1965, "culture", "The Sound of Music", "Robert Wise filmi.", [], None),
        ("1960s", 1966, "culture", "Who's Afraid of Virginia Woolf?", "Elizabeth Taylor filmi.", ["Elizabeth Taylor"], None),
        ("1960s", 1967, "culture", "Bonnie and Clyde", "Warren Beatty filmi.", [], None),
        ("1960s", 1968, "culture", "2001: A Space Odyssey", "Stanley Kubrick filmi.", ["Stanley Kubrick"], None),
        ("1960s", 1969, "culture", "Midnight Cowboy", "John Schlesinger filmi.", ["Jon Voight", "Dustin Hoffman"], None),
        ("1960s", 1960, "culture", "The Flintstones", "Çizgi film.", [], None),
        ("1960s", 1961, "culture", "West Side Story", "Müzikal film.", [], None),
        ("1960s", 1962, "culture", "Dr. No", "İlk James Bond filmi.", ["Sean Connery"], None),
        ("1960s", 1963, "culture", "The Great Escape", "Steve McQueen filmi.", ["Steve McQueen"], None),
        ("1960s", 1964, "culture", "My Fair Lady", "Audrey Hepburn filmi.", [], None),
        ("1960s", 1965, "culture", "Doctor Zhivago", "David Lean filmi.", [], None),
        ("1960s", 1966, "culture", "Batman TV", "Adam West TV dizisi.", ["Adam West"], None),
        ("1960s", 1967, "culture", "The Dirty Dozen", "Lee Marvin filmi.", [], None),
        ("1960s", 1968, "culture", "Planet of the Apes", "Charlton Heston filmi.", [], None),
        ("1960s", 1969, "culture", "Easy Rider", "Dennis Hopper filmi.", ["Dennis Hopper", "Peter Fonda"], None),
        ("1960s", 1960, "culture", "The Andy Griffith Show", "TV dizisi.", [], None),
        ("1960s", 1961, "culture", "101 Dalmatians", "Disney filmi.", [], None),
        ("1960s", 1962, "culture", "Lawrence of Arabia", "David Lean filmi.", [], None),
        ("1960s", 1963, "culture", "Cleopatra", "Elizabeth Taylor filmi.", [], None),
        ("1960s", 1964, "culture", "Goldfinger", "James Bond filmi.", [], None),
        ("1960s", 1965, "culture", "The Sound of Music", "Robert Wise filmi.", [], None),
        ("1960s", 1966, "culture", "The Good, the Bad and the Ugly", "Sergio Leone filmi.", ["Clint Eastwood"], None),

        # 1970s - 50 olay
        ("1970s", 1970, "war", "Kentucky Olayı", "Ulusal Muhafız öğrencilere ateş açtı.", [], 4),
        ("1970s", 1970, "politics", "Environmental Protection Agency", "EPA kuruldu.", [], None),
        ("1970s", 1971, "politics", "Pentagon Papers", "Sızıntılar Vietnam politikalarını eleştirdi.", [], None),
        ("1970s", 1971, "culture", "All in the Family", "TV sitcomu başladı.", [], None),
        ("1970s", 1972, "politics", "Nixon Çin'de", "Nixon tarihi ziyaret yaptı.", ["Richard Nixon", "Mao"], None),
        ("1970s", 1972, "politics", "Watergate Skandalı", "Hırsızlık girişimi ortaya çıktı.", ["Richard Nixon"], None),
        ("1970s", 1973, "politics", "Roe v. Wade", "Kürtaj hakkı tanındı.", [], None),
        ("1970s", 1973, "war", "Vietnam Ateşkes", "ABD askerleri çekildi.", [], None),
        ("1970s", 1973, "culture", "Elvis Hawaii Konseri", "Aloha from Hawaii canlı yayını.", ["Elvis Presley"], None),
        ("1970s", 1974, "politics", "Nixon İstifa", "Watergate sonrası Nixon istifa etti.", ["Richard Nixon"], None),
        ("1970s", 1974, "politics", "Gerald Ford Başkan", "Ford başkanlığa yükseldi.", ["Gerald Ford"], None),
        ("1970s", 1975, "politics", "Saigon Düştü", "Vietnam Savaşı sona erdi.", [], None),
        ("1970s", 1975, "culture", "Jaws Film", "Steven Spielberg filmi.", ["Steven Spielberg"], None),
        ("1970s", 1976, "politics", "Jimmy Carter Başkan", "Carter seçildi.", ["Jimmy Carter"], None),
        ("1970s", 1976, "culture", "Rocky Film", "Sylvester Stallone filmi.", ["Sylvester Stallone"], None),
        ("1970s", 1977, "culture", "Star Wars", "George Lucas filmi devrim yarattı.", ["George Lucas"], None),
        ("1970s", 1977, "culture", "Saturday Night Fever", "John Travolta filmi.", ["John Travolta", "Bee Gees"], None),
        ("1970s", 1978, "culture", "Grease", "Müzikal film.", ["John Travolta", "Olivia Newton-John"], None),
        ("1970s", 1978, "culture", "Superman Film", "Christopher Reeve filmi.", ["Christopher Reeve"], None),
        ("1970s", 1979, "culture", "Alien", "Ridley Scott filmi.", ["Sigourney Weaver"], None),
        ("1970s", 1970, "culture", "Patton", "George C. Scott filmi.", [], None),
        ("1970s", 1971, "culture", "A Clockwork Orange", "Stanley Kubrick filmi.", [], None),
        ("1970s", 1972, "culture", "The Godfather", "Francis Ford Coppola filmi.", ["Marlon Brando", "Al Pacino"], None),
        ("1970s", 1973, "culture", "The Sting", "Paul Newman ve Robert Redford filmi.", [], None),
        ("1970s", 1974, "culture", "The Godfather Part II", "Francis Ford Coppola filmi.", ["Al Pacino", "Robert De Niro"], None),
        ("1970s", 1975, "culture", "One Flew Over the Cuckoo's Nest", "Miloš Forman filmi.", ["Jack Nicholson"], None),
        ("1970s", 1976, "culture", "Rocky", "John G. Avildsen filmi.", [], None),
        ("1970s", 1977, "culture", "Annie Hall", "Woody Allen filmi.", ["Woody Allen", "Diane Keaton"], None),
        ("1970s", 1978, "culture", "The Deer Hunter", "Michael Cimino filmi.", ["Robert De Niro"], None),
        ("1970s", 1979, "culture", "Kramer vs. Kramer", "Dustin Hoffman filmi.", [], None),
        ("1970s", 1970, "culture", "M*A*S*H", "Robert Altman filmi.", [], None),
        ("1970s", 1971, "culture", "The French Connection", "William Friedkin filmi.", ["Gene Hackman"], None),
        ("1970s", 1972, "culture", "Cabaret", "Bob Fosse filmi.", ["Liza Minnelli"], None),
        ("1970s", 1973, "culture", "The Exorcist", "William Friedkin filmi.", [], None),
        ("1970s", 1974, "culture", "Chinatown", "Roman Polanski filmi.", ["Jack Nicholson"], None),
        ("1970s", 1975, "culture", "Jaws", "Steven Spielberg filmi.", [], None),
        ("1970s", 1976, "culture", "Network", "Sidney Lumet filmi.", ["Faye Dunaway"], None),
        ("1970s", 1977, "culture", "Close Encounters", "Steven Spielberg filmi.", [], None),
        ("1970s", 1978, "culture", "Halloween", "John Carpenter filmi.", [], None),
        ("1970s", 1979, "culture", "Apocalypse Now", "Francis Ford Coppola filmi.", ["Marlon Brando", "Martin Sheen"], None),
        ("1970s", 1970, "culture", "Love Story", "Arthur Hiller filmi.", ["Ali MacGraw", "Ryan O'Neal"], None),
        ("1970s", 1971, "culture", "Dirty Harry", "Clint Eastwood filmi.", [], None),
        ("1970s", 1972, "culture", "Deliverance", "John Boorman filmi.", [], None),
        ("1970s", 1973, "culture", "American Graffiti", "George Lucas filmi.", [], None),
        ("1970s", 1974, "culture", "Blazing Saddles", "Mel Brooks filmi.", [], None),
        ("1970s", 1975, "culture", "Dog Day Afternoon", "Sidney Lumet filmi.", ["Al Pacino"], None),
        ("1970s", 1976, "culture", "Taxi Driver", "Martin Scorsese filmi.", ["Robert De Niro"], None),
        ("1970s", 1977, "culture", "Saturday Night Fever", "John Badham filmi.", [], None),
        ("1970s", 1978, "culture", "Superman", "Richard Donner filmi.", [], None),
        ("1970s", 1979, "culture", "Manhattan", "Woody Allen filmi.", [], None),

        # 1980s - 50 olay
        ("1980s", 1980, "politics", "Ronald Reagan Başkan", "Reagan seçildi.", ["Ronald Reagan"], None),
        ("1980s", 1980, "culture", "Empire Strikes Back", "Star Wars devam filmi.", [], None),
        ("1980s", 1981, "terror", "Reagan Suikast Girişimi", "John Hinckley ateş açtı.", ["John Hinckley"], 1),
        ("1980s", 1981, "culture", "MTV", "Music Television yayına başladı.", [], None),
        ("1980s", 1982, "culture", "E.T.", "Steven Spielberg filmi.", [], None),
        ("1980s", 1982, "culture", "Michael Jackson Thriller", "Thriller albümü çıktı.", ["Michael Jackson"], None),
        ("1980s", 1983, "war", "Grenada", "ABD Grenada'yı işgal etti.", [], 19),
        ("1980s", 1983, "culture", "Return of the Jedi", "Star Wars üçlemesi tamamlandı.", [], None),
        ("1980s", 1984, "politics", "Reagan Yeniden", "Reagan ikinci dönem kazandı.", [], None),
        ("1980s", 1984, "culture", "Ghostbusters", "Bill Murray filmi.", [], None),
        ("1980s", 1985, "diplomacy", "Reagan-Gorbachev Zirvesi", "Cenevre zirvesi.", ["Reagan", "Gorbachev"], None),
        ("1980s", 1985, "culture", "Back to the Future", "Robert Zemeckis filmi.", ["Michael J. Fox"], None),
        ("1980s", 1986, "culture", "Chernobyl", "Nükleer felaket ABD'de endişe yarattı.", [], None),
        ("1980s", 1986, "culture", "Top Gun", "Tom Cruise filmi.", ["Tom Cruise"], None),
        ("1980s", 1986, "culture", "Challenger Felaketi", "Uzay mekiği patladı.", [], 7),
        ("1980s", 1987, "war", "INF Anlaşması", "Orta menzilli nükleer kuvvetler anlaşması.", [], None),
        ("1980s", 1987, "culture", "Wall Street", "Oliver Stone filmi.", ["Michael Douglas"], None),
        ("1980s", 1988, "politics", "George H.W. Bush Başkan", "Bush seçildi.", ["George H.W. Bush"], None),
        ("1980s", 1989, "war", "Berlin Duvarı Yıkıldı", "Sovyetlerin çöküşü başladı.", [], None),
        ("1980s", 1989, "culture", "Batman", "Tim Burton filmi.", ["Michael Keaton", "Jack Nicholson"], None),
        ("1980s", 1980, "culture", "The Shining", "Stanley Kubrick filmi.", ["Jack Nicholson"], None),
        ("1980s", 1981, "culture", "Raiders of the Lost Ark", "Steven Spielberg filmi.", ["Harrison Ford"], None),
        ("1980s", 1982, "culture", "Blade Runner", "Ridley Scott filmi.", ["Harrison Ford"], None),
        ("1980s", 1983, "culture", "Scarface", "Brian De Palma filmi.", ["Al Pacino"], None),
        ("1980s", 1984, "culture", "The Terminator", "James Cameron filmi.", ["Arnold Schwarzenegger"], None),
        ("1980s", 1985, "culture", "The Color Purple", "Steven Spielberg filmi.", ["Whoopi Goldberg", "Oprah Winfrey"], None),
        ("1980s", 1986, "culture", "Aliens", "James Cameron filmi.", ["Sigourney Weaver"], None),
        ("1980s", 1987, "culture", "Fatal Attraction", "Adrian Lyne filmi.", ["Michael Douglas", "Glenn Close"], None),
        ("1980s", 1988, "culture", "Rain Man", "Barry Levinson filmi.", ["Dustin Hoffman", "Tom Cruise"], None),
        ("1980s", 1989, "culture", "Dead Poets Society", "Peter Weir filmi.", ["Robin Williams"], None),
        ("1980s", 1980, "culture", "Airplane!", "Komedi filmi.", [], None),
        ("1980s", 1981, "culture", "Chariots of Fire", "Hugh Hudson filmi.", [], None),
        ("1980s", 1982, "culture", "Gandhi", "Richard Attenborough filmi.", ["Ben Kingsley"], None),
        ("1980s", 1983, "culture", "The Big Chill", "Lawrence Kasdan filmi.", [], None),
        ("1980s", 1984, "culture", "Amadeus", "Miloš Forman filmi.", ["F. Murray Abraham", "Tom Hulce"], None),
        ("1980s", 1985, "culture", "Out of Africa", "Sydney Pollack filmi.", ["Meryl Streep", "Robert Redford"], None),
        ("1980s", 1986, "culture", "Platoon", "Oliver Stone filmi.", ["Charlie Sheen", "Willem Dafoe"], None),
        ("1980s", 1987, "culture", "Good Morning, Vietnam", "Barry Levinson filmi.", ["Robin Williams"], None),
        ("1980s", 1988, "culture", "Big", "Penny Marshall filmi.", ["Tom Hanks"], None),
        ("1980s", 1989, "culture", "Driving Miss Daisy", "Bruce Beresford filmi.", ["Morgan Freeman", "Jessica Tandy"], None),
        ("1980s", 1980, "culture", "The Blues Brothers", "John Landis filmi.", ["John Belushi", "Dan Aykroyd"], None),
        ("1980s", 1981, "culture", "On Golden Pond", "Mark Rydell filmi.", ["Katharine Hepburn", "Henry Fonda"], None),
        ("1980s", 1982, "culture", "Poltergeist", "Tobe Hooper filmi.", [], None),
        ("1980s", 1983, "culture", "Risky Business", "Paul Brickman filmi.", ["Tom Cruise"], None),
        ("1980s", 1984, "culture", "Beverly Hills Cop", "Martin Brest filmi.", ["Eddie Murphy"], None),
        ("1980s", 1985, "culture", "The Breakfast Club", "John Hughes filmi.", ["Emilio Estevez", "Molly Ringwald"], None),
        ("1980s", 1986, "culture", "Ferris Bueller's Day Off", "John Hughes filmi.", ["Matthew Broderick"], None),
        ("1980s", 1987, "culture", "Full Metal Jacket", "Stanley Kubrick filmi.", [], None),
        ("1980s", 1988, "culture", "Die Hard", "John McTiernan filmi.", ["Bruce Willis"], None),
        ("1980s", 1989, "culture", "When Harry Met Sally", "Rob Reiner filmi.", ["Billy Crystal", "Meg Ryan"], None),

        # 1990s - 50 olay
        ("1990s", 1990, "war", "Körfez Savaşı", "Kuveyt'i kurtarma operasyonu.", ["George H.W. Bush"], 300),
        ("1990s", 1990, "culture", "Goodfellas", "Martin Scorsese filmi.", ["Robert De Niro", "Joe Pesci"], None),
        ("1990s", 1991, "war", "Sovyetlerin Çöküşü", "Soğuk Savaş sona erdi.", [], None),
        ("1990s", 1991, "culture", "Silence of the Lambs", "Jonathan Demme filmi.", ["Jodie Foster", "Anthony Hopkins"], None),
        ("1990s", 1992, "politics", "Bill Clinton Başkan", "Clinton seçildi.", ["Bill Clinton"], None),
        ("1990s", 1992, "culture", "Unforgiven", "Clint Eastwood filmi.", [], None),
        ("1990s", 1993, "terror", "Dünya Ticaret Merkezi", "Bombalı saldırı.", [], 6),
        ("1990s", 1993, "politics", "NAFTA", "Kuzey Amerika Serbest Ticaret Anlaşması.", [], None),
        ("1990s", 1993, "culture", "Jurassic Park", "Steven Spielberg filmi.", [], None),
        ("1990s", 1994, "politics", "Republican Revolution", "Cumhuriyetçiler Kongre'yi ele geçirdi.", ["Newt Gingrich"], None),
        ("1990s", 1994, "culture", "Pulp Fiction", "Quentin Tarantino filmi.", ["John Travolta", "Samuel L. Jackson"], None),
        ("1990s", 1995, "terror", "Oklahoma City", "Bombalı saldırı.", ["Timothy McVeigh"], 168),
        ("1990s", 1995, "culture", "Toy Story", "İlk tam bilgisayar animasyon film.", ["Pixar"], None),
        ("1990s", 1996, "politics", "Clinton Yeniden", "Clinton ikinci dönem kazandı.", [], None),
        ("1990s", 1996, "culture", "Independence Day", "Roland Emmerich filmi.", ["Will Smith"], None),
        ("1990s", 1997, "culture", "Titanic", "James Cameron filmi rekor kırdı.", ["Leonardo DiCaprio", "Kate Winslet"], None),
        ("1990s", 1998, "politics", "Clinton İmpeachment", "Clinton azledildi ama aklandı.", [], None),
        ("1990s", 1998, "culture", "Saving Private Ryan", "Steven Spielberg filmi.", ["Tom Hanks"], None),
        ("1990s", 1999, "culture", "The Matrix", "Wachowski kardeşler filmi.", ["Keanu Reeves"], None),
        ("1990s", 1990, "culture", "Dances with Wolves", "Kevin Costner filmi.", [], None),
        ("1990s", 1991, "culture", "Thelma & Louise", "Ridley Scott filmi.", ["Geena Davis", "Susan Sarandon"], None),
        ("1990s", 1992, "culture", "Unforgiven", "Clint Eastwood filmi.", ["Clint Eastwood", "Gene Hackman"], None),
        ("1990s", 1993, "culture", "Schindler's List", "Steven Spielberg filmi.", ["Liam Neeson", "Ralph Fiennes"], None),
        ("1990s", 1994, "culture", "Forrest Gump", "Robert Zemeckis filmi.", ["Tom Hanks"], None),
        ("1990s", 1995, "culture", "Braveheart", "Mel Gibson filmi.", ["Mel Gibson"], None),
        ("1990s", 1996, "culture", "Fargo", "Coen kardeşler filmi.", ["Frances McDormand"], None),
        ("1990s", 1997, "culture", "L.A. Confidential", "Curtis Hanson filmi.", ["Kevin Spacey", "Russell Crowe"], None),
        ("1990s", 1998, "culture", "Shakespeare in Love", "John Madden filmi.", ["Gwyneth Paltrow", "Joseph Fiennes"], None),
        ("1990s", 1999, "culture", "American Beauty", "Sam Mendes filmi.", ["Kevin Spacey", "Annette Bening"], None),
        ("1990s", 1990, "culture", "Pretty Woman", "Garry Marshall filmi.", ["Julia Roberts", "Richard Gere"], None),
        ("1990s", 1991, "culture", "Terminator 2", "James Cameron filmi.", ["Arnold Schwarzenegger"], None),
        ("1990s", 1992, "culture", "A Few Good Men", "Rob Reiner filmi.", ["Tom Cruise", "Jack Nicholson"], None),
        ("1990s", 1993, "culture", "Philadelphia", "Jonathan Demme filmi.", ["Tom Hanks", "Denzel Washington"], None),
        ("1990s", 1994, "culture", "The Shawshank Redemption", "Frank Darabont filmi.", ["Tim Robbins", "Morgan Freeman"], None),
        ("1990s", 1995, "culture", "Apollo 13", "Ron Howard filmi.", ["Tom Hanks"], None),
        ("1990s", 1996, "culture", "Jerry Maguire", "Cameron Crowe filmi.", ["Tom Cruise", "Renée Zellweger"], None),
        ("1990s", 1997, "culture", "Good Will Hunting", "Gus Van Sant filmi.", ["Matt Damon", "Ben Affleck", "Robin Williams"], None),
        ("1990s", 1998, "culture", "The Big Lebowski", "Coen kardeşler filmi.", ["Jeff Bridges", "John Goodman"], None),
        ("1990s", 1999, "culture", "Fight Club", "David Fincher filmi.", ["Brad Pitt", "Edward Norton"], None),
        ("1990s", 1990, "culture", "Home Alone", "Chris Columbus filmi.", ["Macaulay Culkin"], None),
        ("1990s", 1991, "culture", "The Silence of the Lambs", "Jonathan Demme filmi.", [], None),
        ("1990s", 1992, "culture", "Reservoir Dogs", "Quentin Tarantino filmi.", ["Harvey Keitel", "Tim Roth"], None),
        ("1990s", 1993, "culture", "Jurassic Park", "Steven Spielberg filmi.", ["Sam Neill", "Laura Dern"], None),
        ("1990s", 1994, "culture", "Léon", "Luc Besson filmi.", ["Jean Reno", "Natalie Portman"], None),
        ("1990s", 1995, "culture", "Se7en", "David Fincher filmi.", ["Brad Pitt", "Morgan Freeman"], None),
        ("1990s", 1996, "culture", "Scream", "Wes Craven filmi.", ["Neve Campbell"], None),
        ("1990s", 1997, "culture", "Men in Black", "Barry Sonnenfeld filmi.", ["Will Smith", "Tommy Lee Jones"], None),
        ("1990s", 1998, "culture", "Rush Hour", "Brett Ratner filmi.", ["Jackie Chan", "Chris Tucker"], None),
        ("1990s", 1999, "culture", "The Sixth Sense", "M. Night Shyamalan filmi.", ["Bruce Willis", "Haley Joel Osment"], None),

        # 2000s - 50 olay
        ("2000s", 2000, "politics", "Bush v. Gore", "Seçimler mahkemeye gitti.", ["George W. Bush", "Al Gore"], None),
        ("2000s", 2000, "culture", "Gladiator", "Ridley Scott filmi.", ["Russell Crowe"], None),
        ("2000s", 2001, "terror", "11 Eylül Saldırıları", "El Kaide dünya ticaret merkezine saldırdı.", ["Osama bin Laden"], 3000),
        ("2000s", 2001, "war", "Afganistan", "ABD Afganistan'ı işgal etti.", [], None),
        ("2000s", 2001, "culture", "Harry Potter Film", "İlk film vizyona girdi.", ["Daniel Radcliffe"], None),
        ("2000s", 2002, "culture", "The Lord of the Rings", "Yüzüklerin Efendisi üçlemesi.", ["Peter Jackson"], None),
        ("2000s", 2002, "war", "Guantanamo", "Tutuklular için kamp açıldı.", [], None),
        ("2000s", 2003, "war", "Irak Savaşı", "ABD Irak'ı işgal etti.", ["George W. Bush"], None),
        ("2000s", 2003, "culture", "Finding Nemo", "Pixar filmi.", [], None),
        ("2000s", 2004, "politics", "George W. Bush Yeniden", "Bush ikinci dönem kazandı.", [], None),
        ("2000s", 2004, "culture", "The Incredibles", "Pixar süper kahraman filmi.", [], None),
        ("2000s", 2004, "culture", "Facebook", "Mark Zuckerberg Facebook'u kurdu.", ["Mark Zuckerberg"], None),
        ("2000s", 2005, "culture", "YouTube", "Video paylaşım sitesi kuruldu.", [], None),
        ("2000s", 2005, "culture", "Katrina Kasırgası", "Yeni Orleans'ı vuran felaket.", [], 1836),
        ("2000s", 2006, "culture", "Twitter", "Sosyal medya platformu kuruldu.", ["Jack Dorsey"], None),
        ("2000s", 2006, "culture", "iPhone", "Apple ilk akıllı telefonunu piyasaya sürdü.", ["Steve Jobs"], None),
        ("2000s", 2007, "culture", "The Dark Knight", "Christopher Nolan filmi.", ["Heath Ledger", "Christian Bale"], None),
        ("2000s", 2007, "culture", "iPhone", "Steve Jobs iPhone'u tanıttı.", ["Steve Jobs"], None),
        ("2000s", 2008, "politics", "Barack Obama Başkan", "İlk siyahi başkan seçildi.", ["Barack Obama"], None),
        ("2000s", 2008, "culture", "Iron Man", "Marvel Sinematik Evreni başladı.", ["Robert Downey Jr."], None),
        ("2000s", 2009, "politics", "Obama İktidarda", "Obama ilk dönemini başlattı.", [], None),
        ("2000s", 2009, "culture", "Avatar", "James Cameron filmi.", ["James Cameron", "Sam Worthington"], None),
        ("2000s", 2000, "culture", "Cast Away", "Robert Zemeckis filmi.", ["Tom Hanks"], None),
        ("2000s", 2001, "culture", "A Beautiful Mind", "Ron Howard filmi.", ["Russell Crowe", "Jennifer Connelly"], None),
        ("2000s", 2002, "culture", "Chicago", "Rob Marshall filmi.", ["Renée Zellweger", "Catherine Zeta-Jones"], None),
        ("2000s", 2003, "culture", "The Lord of the Rings: Return of the King", "Peter Jackson filmi.", [], None),
        ("2000s", 2004, "culture", "Million Dollar Baby", "Clint Eastwood filmi.", ["Hilary Swank", "Morgan Freeman"], None),
        ("2000s", 2005, "culture", "Crash", "Paul Haggis filmi.", ["Sandra Bullock", "Don Cheadle"], None),
        ("2000s", 2006, "culture", "The Departed", "Martin Scorsese filmi.", ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson"], None),
        ("2000s", 2007, "culture", "No Country for Old Men", "Coen kardeşler filmi.", ["Javier Bardem", "Tommy Lee Jones"], None),
        ("2000s", 2008, "culture", "Slumdog Millionaire", "Danny Boyle filmi.", [], None),
        ("2000s", 2009, "culture", "The Hurt Locker", "Kathryn Bigelow filmi.", ["Jeremy Renner"], None),
        ("2000s", 2000, "culture", "X-Men", "Bryan Singer filmi.", ["Hugh Jackman", "Patrick Stewart"], None),
        ("2000s", 2001, "culture", "Harry Potter and the Sorcerer's Stone", "Chris Columbus filmi.", [], None),
        ("2000s", 2002, "culture", "Spider-Man", "Sam Raimi filmi.", ["Tobey Maguire", "Kirsten Dunst"], None),
        ("2000s", 2003, "culture", "Pirates of the Caribbean", "Gore Verbinski filmi.", ["Johnny Depp", "Orlando Bloom"], None),
        ("2000s", 2004, "culture", "The Passion of the Christ", "Mel Gibson filmi.", ["Jim Caviezel"], None),
        ("2000s", 2005, "culture", "Batman Begins", "Christopher Nolan filmi.", ["Christian Bale"], None),
        ("2000s", 2006, "culture", "Cars", "John Lasseter filmi.", [], None),
        ("2000s", 2007, "culture", "Ratatouille", "Brad Bird filmi.", [], None),
        ("2000s", 2008, "culture", "WALL-E", "Andrew Stanton filmi.", [], None),
        ("2000s", 2009, "culture", "Up", "Pete Docter filmi.", [], None),
        ("2000s", 2000, "culture", "Mission: Impossible II", "John Woo filmi.", ["Tom Cruise"], None),
        ("2000s", 2001, "culture", "Shrek", "Andrew Adamson filmi.", ["Mike Myers", "Eddie Murphy"], None),
        ("2000s", 2002, "culture", "Star Wars: Episode II", "George Lucas filmi.", ["Ewan McGregor", "Natalie Portman"], None),
        ("2000s", 2003, "culture", "The Matrix Reloaded", "Wachowski kardeşler filmi.", ["Keanu Reeves"], None),
        ("2000s", 2004, "culture", "Shrek 2", "Andrew Adamson filmi.", [], None),
        ("2000s", 2005, "culture", "Star Wars: Episode III", "George Lucas filmi.", [], None),
        ("2000s", 2006, "culture", "The Da Vinci Code", "Ron Howard filmi.", ["Tom Hanks"], None),
        ("2000s", 2007, "culture", "Spider-Man 3", "Sam Raimi filmi.", ["Tobey Maguire"], None),
        ("2000s", 2008, "culture", "The Dark Knight", "Christopher Nolan filmi.", ["Heath Ledger"], None),
        ("2000s", 2009, "culture", "Transformers: Revenge of the Fallen", "Michael Bay filmi.", ["Shia LaBeouf", "Megan Fox"], None),

        # 2010s - 50 olay
        ("2010s", 2010, "culture", "The Social Network", "David Fincher filmi.", ["Jesse Eisenberg"], None),
        ("2010s", 2010, "culture", "Toy Story 3", "Lee Unkrich filmi.", [], None),
        ("2010s", 2010, "politics", "Obama Healthcare", "Sağlık reformu yasalaştı.", [], None),
        ("2010s", 2010, "culture", "Instagram", "Fotoğraf paylaşım uygulaması.", [], None),
        ("2010s", 2011, "terror", "Osama bin Laden Öldürüldü", "Navy SEALS operasyonu.", [], 1),
        ("2010s", 2011, "culture", "Game of Thrones", "HBO dizisi başladı.", [], None),
        ("2010s", 2011, "culture", "Harry Potter Son Film", "Seri sona erdi.", [], None),
        ("2010s", 2012, "culture", "The Avengers", "Marvel süper kahraman filmi.", [], None),
        ("2010s", 2012, "politics", "Obama Yeniden Seçildi", "Obama ikinci dönem kazandı.", [], None),
        ("2010s", 2012, "culture", "Gangnam Style", "YouTube'da 1 milyar izlenme.", [], None),
        ("2010s", 2013, "culture", "Frozen", "Disney animasyon.", [], None),
        ("2010s", 2013, "politics", "Snowden Sızıntıları", "NSA belgeleri sızdırıldı.", ["Edward Snowden"], None),
        ("2010s", 2014, "culture", "Guardians of the Galaxy", "Marvel filmi.", ["Chris Pratt"], None),
        ("2010s", 2014, "politics", "Ferguson", "Polis şiddeti protestoları.", ["Michael Brown"], None),
        ("2010s", 2015, "culture", "Star Wars: The Force Awakens", "J.J. Abrams filmi.", [], None),
        ("2010s", 2015, "politics", "Same-Sex Marriage", "Eşcinsel evlilik yasallaştı.", [], None),
        ("2010s", 2016, "politics", "Donald Trump Başkan", "Trump seçildi.", ["Donald Trump"], None),
        ("2010s", 2016, "culture", "Stranger Things", "Netflix dizisi.", [], None),
        ("2010s", 2016, "culture", "Captain America: Civil War", "Marvel filmi.", [], None),
        ("2010s", 2017, "politics", "Trump İktidarda", "Trump ilk dönemini başlattı.", [], None),
        ("2010s", 2017, "culture", "Wonder Woman", "DC Comics filmi.", ["Gal Gadot"], None),
        ("2010s", 2017, "culture", "Get Out", "Jordan Peele filmi.", [], None),
        ("2010s", 2018, "culture", "Black Panther", "Marvel filmi.", ["Chadwick Boseman"], None),
        ("2010s", 2018, "politics", "Kavanaugh Hearing", "Yüksek mahkeme adayı duruşması.", [], None),
        ("2010s", 2019, "culture", "Avengers: Endgame", "Marvel filmi gişe rekoru kırdı.", [], None),
        ("2010s", 2019, "politics", "Trump İmpeachment", "Trump azledildi ama aklandı.", [], None),
        ("2010s", 2010, "culture", "Inception", "Christopher Nolan filmi.", ["Leonardo DiCaprio"], None),
        ("2010s", 2011, "culture", "The Artist", "Sessiz film.", ["Jean Dujardin"], None),
        ("2010s", 2012, "culture", "Argo", "Ben Affleck filmi.", [], None),
        ("2010s", 2013, "culture", "12 Years a Slave", "Steve McQueen filmi.", ["Chiwetel Ejiofor", "Lupita Nyong'o"], None),
        ("2010s", 2014, "culture", "Birdman", "Alejandro G. Iñárritu filmi.", ["Michael Keaton"], None),
        ("2010s", 2015, "culture", "Spotlight", "Tom McCarthy filmi.", ["Michael Keaton", "Mark Ruffalo"], None),
        ("2010s", 2016, "culture", "Moonlight", "Barry Jenkins filmi.", [], None),
        ("2010s", 2017, "culture", "The Shape of Water", "Guillermo del Toro filmi.", ["Sally Hawkins"], None),
        ("2010s", 2018, "culture", "Green Book", "Peter Farrelly filmi.", ["Viggo Mortensen", "Mahershala Ali"], None),
        ("2010s", 2019, "culture", "Parasite", "Bong Joon-ho filmi.", [], None),
        ("2010s", 2010, "culture", "Iron Man 2", "Jon Favreau filmi.", ["Robert Downey Jr."], None),
        ("2010s", 2011, "culture", "Thor", "Kenneth Branagh filmi.", ["Chris Hemsworth"], None),
        ("2010s", 2011, "culture", "Captain America", "Joe Johnston filmi.", ["Chris Evans"], None),
        ("2010s", 2012, "culture", "The Amazing Spider-Man", "Marc Webb filmi.", ["Andrew Garfield"], None),
        ("2010s", 2013, "culture", "Man of Steel", "Zack Snyder filmi.", ["Henry Cavill"], None),
        ("2010s", 2014, "culture", "Captain America: The Winter Soldier", "Russo kardeşler filmi.", ["Chris Evans"], None),
        ("2010s", 2015, "culture", "Star Wars: The Force Awakens", "J.J. Abrams filmi.", ["Daisy Ridley", "John Boyega"], None),
        ("2010s", 2016, "culture", "Deadpool", "Tim Miller filmi.", ["Ryan Reynolds"], None),
        ("2010s", 2017, "culture", "Logan", "James Mangold filmi.", ["Hugh Jackman"], None),
        ("2010s", 2018, "culture", "Avengers: Infinity War", "Russo kardeşler filmi.", ["Josh Brolin"], None),
        ("2010s", 2019, "culture", "Joker", "Todd Phillips filmi.", ["Joaquin Phoenix"], None),
        ("2010s", 2019, "culture", "The Irishman", "Martin Scorsese filmi.", ["Robert De Niro", "Al Pacino", "Joe Pesci"], None),
        ("2010s", 2010, "culture", "Despicable Me", "Pierre Coffin filmi.", [], None),
        ("2010s", 2011, "culture", "Fast Five", "Justin Lin filmi.", ["Vin Diesel", "Paul Walker"], None),
        ("2010s", 2012, "culture", "The Hunger Games", "Gary Ross filmi.", ["Jennifer Lawrence"], None),
        ("2010s", 2013, "culture", "Frozen", "Chris Buck filmi.", ["Idina Menzel", "Kristen Bell"], None),
        ("2010s", 2014, "culture", "The Lego Movie", "Phil Lord filmi.", [], None),
        ("2010s", 2015, "culture", "Jurassic World", "Colin Trevorrow filmi.", ["Chris Pratt"], None),

        # 2020s - 50 olay
        ("2020s", 2020, "culture", "COVID-19 Pandemisi", "ABD'de pandemi başladı.", [], 1100000),
        ("2020s", 2020, "politics", "Trump İmpeachment", "Trump ikinci kez azledildi.", [], None),
        ("2020s", 2020, "politics", "George Floyd Protestoları", "BLM protestoları.", [], None),
        ("2020s", 2020, "politics", "Joe Biden Başkan", "Biden seçildi.", ["Joe Biden"], None),
        ("2020s", 2021, "politics", "Capitol Saldırısı", "Trump destekçileri kongreye saldırdı.", [], 5),
        ("2020s", 2021, "politics", "Biden İktidarda", "Biden başkanlık görevine başladı.", [], None),
        ("2020s", 2021, "culture", "Squid Game", "Netflix dizisi fenomen oldu.", [], None),
        ("2020s", 2021, "culture", "Spider-Man: No Way Home", "Marvel filmi pandemi gişe rekoru kırdı.", ["Tom Holland"], None),
        ("2020s", 2022, "politics", "Rusya-Ukrayna", "ABD Ukrayna'ya yardım etti.", [], None),
        ("2020s", 2022, "politics", "Roe v. Wade Kaldırıldı", "Kürtaj hakkı kararı iptal edildi.", [], None),
        ("2020s", 2022, "culture", "Top Gun: Maverick", "Tom Cruise filmi.", ["Tom Cruise"], None),
        ("2020s", 2023, "politics", "Trump Tutuklama", "Trump tarihte ilk kez tutuklandı.", [], None),
        ("2020s", 2023, "culture", "Barbie Film", "Greta Gerwig filmi.", ["Margot Robbie", "Ryan Gosling"], None),
        ("2020s", 2023, "culture", "Oppenheimer", "Christopher Nolan filmi.", ["Cillian Murphy"], None),
        ("2020s", 2024, "politics", "Trump Yeniden Seçildi", "Trump ikinci dönem için seçildi.", ["Donald Trump"], None),
        ("2020s", 2024, "culture", "Inside Out 2", "Pixar filmi.", [], None),
        ("2020s", 2024, "politics", "Biden Adaylıktan Çekildi", "Biden seçimlerden çekildi.", [], None),
        ("2020s", 2024, "politics", "Harris Aday", "Kamala Harris başkan adayı oldu.", ["Kamala Harris"], None),
        ("2020s", 2025, "politics", "Trump İkinci Dönem", "Trump ikinci başkanlık dönemine başladı.", [], None),
        ("2020s", 2025, "culture", "Moana 2", "Disney filmi.", [], None),
        ("2020s", 2020, "culture", "Nomadland", "Chloé Zhao filmi.", ["Frances McDormand"], None),
        ("2020s", 2021, "culture", "CODA", "Sian Heder filmi.", [], None),
        ("2020s", 2022, "culture", "Everything Everywhere All at Once", "Daniels filmi.", ["Michelle Yeoh"], None),
        ("2020s", 2023, "culture", "Oppenheimer", "Christopher Nolan filmi.", [], None),
        ("2020s", 2024, "culture", "Anora", "Sean Baker filmi.", [], None),
        ("2020s", 2020, "culture", "Tenet", "Christopher Nolan filmi.", ["John David Washington"], None),
        ("2020s", 2021, "culture", "Dune", "Denis Villeneuve filmi.", ["Timothée Chalamet"], None),
        ("2020s", 2021, "culture", "Spider-Man: No Way Home", "Jon Watts filmi.", [], None),
        ("2020s", 2022, "culture", "The Batman", "Matt Reeves filmi.", ["Robert Pattinson"], None),
        ("2020s", 2023, "culture", "The Super Mario Bros. Movie", "Aaron Horvath filmi.", [], None),
        ("2020s", 2023, "culture", "Guardians of the Galaxy Vol. 3", "James Gunn filmi.", [], None),
        ("2020s", 2024, "culture", "Deadpool & Wolverine", "Shawn Levy filmi.", ["Ryan Reynolds", "Hugh Jackman"], None),
        ("2020s", 2024, "culture", "Wicked", "Jon M. Chu filmi.", ["Cynthia Erivo", "Ariana Grande"], None),
        ("2020s", 2025, "culture", "Captain America: Brave New World", "Julius Onah filmi.", [], None),
        ("2020s", 2025, "culture", "Snow White", "Marc Webb filmi.", [], None),
        ("2020s", 2020, "culture", "Hamilton Disney+", "Lin-Manuel Miranda müzikali.", [], None),
        ("2020s", 2021, "culture", "WandaVision", "Disney+ dizisi.", ["Elizabeth Olsen", "Paul Bettany"], None),
        ("2020s", 2021, "culture", "Loki", "Disney+ dizisi.", ["Tom Hiddleston"], None),
        ("2020s", 2022, "culture", "House of the Dragon", "HBO dizisi.", [], None),
        ("2020s", 2022, "culture", "The Lord of the Rings: The Rings of Power", "Amazon dizisi.", [], None),
        ("2020s", 2023, "culture", "The Last of Us", "HBO dizisi.", ["Pedro Pascal", "Bella Ramsey"], None),
        ("2020s", 2024, "culture", "Shōgun", "FX dizisi.", [], None),
        ("2020s", 2024, "culture", "Baby Reindeer", "Netflix dizisi.", [], None),
        ("2020s", 2025, "culture", "Severance", "Apple TV+ dizisi.", [], None),
        ("2020s", 2020, "culture", "Zoom", "Video konferans patlaması.", [], None),
        ("2020s", 2021, "culture", "TikTok", "Sosyal medya platformu zirve yaptı.", [], None),
        ("2020s", 2022, "culture", "Wordle", "Kelime oyunu fenomen oldu.", [], None),
        ("2020s", 2023, "culture", "ChatGPT", "Yapay zeka devrimi.", ["Sam Altman"], None),
        ("2020s", 2024, "culture", "Apple Vision Pro", "AR gözlüğü tanıtıldı.", [], None),
        ("2020s", 2025, "culture", "Sora", "OpenAI video yapay zekası.", [], None),
    ]
    
    for event_data in usa_events_data:
        decade, year, category, title, description, key_figures, casualties = event_data
        
        event = {
            "country_code": usa_data["country_code"],
            "country_name": usa_data["country_name"],
            "lat": usa_data["lat"],
            "lon": usa_data["lon"],
            "decade": decade,
            "year": year,
            "category": category,
            "title": title,
            "description": description,
            "wikipedia_url": "",
            "casualties": casualties,
            "key_figures": key_figures,
            "id": f"ev{uuid.uuid4().hex[:8]}"
        }
        events.append(event)
    
    return events


def main():
    # Yeni olayları üret
    new_events = generate_usa_events()
    print(f"Üretilen ABD olayı: {len(new_events)}")
    
    # Mevcut events.json'u oku
    data_path = Path(__file__).parent.parent / "data" / "events.json"
    with open(data_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Mevcut olay sayısı
    existing_count = len(data['events'])
    print(f"Mevcut toplam olay: {existing_count}")
    
    # Yeni olayları ekle
    data['events'].extend(new_events)
    
    # Kaydet
    with open(data_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"Yeni toplam olay: {len(data['events'])}")
    print(f"Eklenen ABD olayı: {len(new_events)}")
    
    # İstatistik
    usa_events = [e for e in data['events'] if e.get('country_code') == 'US']
    by_decade = {}
    for e in usa_events:
        d = e.get('decade', 'unknown')
        by_decade[d] = by_decade.get(d, 0) + 1
    
    print("\nDekadlara göre toplam ABD olayları:")
    for d in sorted(by_decade.keys()):
        print(f"  {d}: {by_decade[d]} olay")
    
    print(f"\nToplam ABD olayı: {len(usa_events)}")


if __name__ == "__main__":
    main()
